### ISSUE TITLE
As an admin you can unflag a session after it has been corrected by rider or admin

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#100]
As an admin you can unflag a session after it has been corrected by rider or admin

**Comment by djong1** [comment]
Note: create an unflag session button on the session page for admin role.

**Comment by djong1** [comment]
deployed

**Comment by jhdebruin** [comment]
@djong1  Works like a charme.... i've updated all sessions in 2023, 

Could you please unflag all previous years, so we can start with a blank sheet for this new procedure, thnx !!

**Comment by jhdebruin** [comment]
Still see them in the list @djong1

**Comment by djong1** [comment]
not all, but removed all now
