### ISSUE TITLE
Unable to conect on foilsurfing

### ISSUE THREAD

**Issue by Nola56** [djong1/gp3s#105]
the page doesn't work on my two laptop with chrome (apple) 

message error 

Sorry...it's not you it's us. oh no an Error 500

We're experiencing an internal server problem.

thx

**Comment by jhdebruin** [comment]
Using Chrome and a Macbook also, no issues here, could you please describe at what step you get this error message ? @Nola56  , and maybe add some screenshots of the screens just before the error 500

**Comment by jhdebruin** [comment]
Problem solved without any additional actions
