### ISSUE TITLE
Update function to delete user from event

### ISSUE THREAD

**Issue by djong1** [djong1/gp3s#108]
After the multi event update it is not possible anymore to delete a user via the Admin module from an event if requested.

**Comment by blinki-bill** [comment]
Its also not possible to delete a session.

**Comment by djong1** [comment]
Admin module is updated, it is now possible to:

1.  rebuild a ranking for an individual user in the event 
2.  remove the user from the event (the user can assign itself to the event again, that is not blocked. When reassigning the event ranking for the user is recreated). 

This function is in Beta release so it would be great if you can test it out and report issues here.

**Comment by blinki-bill** [comment]
The new module can’t be reached with my status. I checked chrome, ff, ie and Safari. Selecting the event and nothing happens at all. 
![4ECF333D-4892-4C13-8A28-2C4DC82EA433](https://user-images.githubusercontent.com/122306619/211836077-434b2e52-77f6-4af7-b17f-0a8ecebff8dd.png)

**Comment by blinki-bill** [comment]
Selecting one of the former Events is possible. I delete the 2014 and 2015 Events. But with 2023 One-Hour-Challenge it does not work. The Event Editor does not open after selection.

**Comment by blinki-bill** [comment]
Still can’t edit anything anymore.

**Comment by jhdebruin** [comment]
Thats pretty strange, we can not reproduce this issue here, we can admin and edit all other events.  Just a quick test, could you setup a second event just for test and see if you can admin / edit if afterwards ?  @blinki-bill 

Event is running for the whole year, so still some time to fix it 😃

**Comment by blinki-bill** [comment]
Ahoi Jan,
thanks for the answer and the work.
Here are some other strange things:
Creating a new event allows me to edit the 2023 One Our Event!
It seems, that the error is in the selection field where i have to choose the event. If i select the Test Event, the 2023 One Our Event will be shown. Same as if i select the 2023 One Our Event. So it themes, that it is not possible to select the first event in the list. Please, check this.
And another thing that does not work at all is removing a user from the event. Even if i wait for more than 5 hours the deleted users still listed in event subscriber list in the over view of the event.
Maybe i have to delete first the Run from the user and then the user?
Have a nice Weekend 
Werner

**Comment by jhdebruin** [comment]
Ok, thnx for the feedback, just tested this and i see the issue now, when playing with the pull down list you can actually edit the event (as workaround), is now clear what to do to fix it -> @djong1 as discussed today at Boot Dusseldorf

**Comment by djong1** [comment]
@blinki-bill Thanks for the input, this helped to solve the issue! I have published a new version, please update us when you had ability to test it.

**Comment by blinki-bill** [comment]
Hey, works fine now! Thank you.
Only exception: when i delete a user the site will be rebuilt and the newest Event is going to be selected. But its the test Event and i am going to delete it so it won't be a problem for me.

**Comment by blinki-bill** [comment]
Hey gp3s Team,
will you please have a look at the event. Now its possible for the deleted Users (Ant Dunn and Steve Brown from Australia) to upload their tracks to the event while they are not subscribed anymore because of being deleted. Even they did not being listed in the Event-Subscribers List but shown in Ranking and Session List.
