### ISSUE TITLE
API issue - issue retrieveing event sessions for foil, wing, kite and ice

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#109]
I seem unable to retrieve event sessions for a number of the platforms.

This can be tested via the following URL:

https://apimgp3s.portal.azure-api.net/docs/services/gps-icesailing-api-v2/operations/Eventsessions/console

Using the "try it" feature, "2022 Estonian Speed King" (event ID = 718) does not return any data.

This is tripping up my Python script that processes event data but is easily demonstrated as above.

It appears to affect all APIs except gps-speedsurfing; i.e. foil, wing, kite, ice are all affected.

**Comment by djong1** [comment]
fixed, thanks for reporting
