### ISSUE TITLE
"Ghost speeds" in rankings and personal bests

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#11]
There are several closely related issues within this single issue.

1) The UK foil rankings contain some "ghost speeds" for Ben Clothier.

   - [Overall rankings by country - UK, average speed](https://www.gps-foilsurfing.com/default.aspx?mnu=rankings&Year1=-&countryID1=268&Gender1=0&Tab=1&WeightClass1=0&AgeClass1=0&SpeedType1=0) – e.g. 29.07 knot average in the rankings for a day he posted 21.97 knots.
   - He is also ranked highly in other speed categories, yet his foil sessions are no faster than 24 knots.
   - Presumably this was caused by a windsurfing session that was posted on the foil site and subsequently deleted.

2) Ben's [personal bests](https://www.gps-foilsurfing.com/default.aspx?mnu=user&smnu=personalbest&uid=24525) also contain the "ghost speeds" relating to a session (or sessions) which have since been deleted.

3) It is also worth noting that this issue of "ghost speeds" also exists on gps-speedsurfing:

   - [Portland Harbour 500m](https://www.gps-speedsurfing.com/default.aspx?mnu=rankings&Year2=-&countryID2=268&SpotID2=681&Gender2=0&Tab=2&WeightClass2=0&AgeClass2=0&SpeedType2=3) - Matthew Spooner (ranked 11) is listed for a session that has been deleted due to car speeds.
   - [Portland Harbour 1852m](https://www.gps-speedsurfing.com/default.aspx?mnu=rankings&Year2=-&countryID2=268&SpotID2=681&Gender2=0&Tab=2&WeightClass2=0&AgeClass2=0&SpeedType2=7) - Tyler Baker (ranked 9) is listed for a session that has been deleted due to car speeds.

**Comment by djong1** [comment]
Thanks for reporting, the bug is identified and fixed. This fix does not apply to the current rankings, we still need to work on a script to rebuild the rankings for users that are affected by this bug. In the time between now and the rebuild you can report riders that are affected and we can update the rankings on a per rider bases.

**Comment by Logiqx** [comment]
Here are two IDs that need rebuilding on gps-speedsurfing:

5246 - Matthew Spooner
22323 - Tyler Baker

Here is one user ID that needs rebuilding on gps-foilsurfing:

24525 - Ben Clothier

**Comment by jhdebruin** [comment]
@Logiqx I've done some rebuilds on on the specified UID's, could you confirm this is ok now ?

**Comment by Logiqx** [comment]
gps-speedsurfing (Matthew and Tyler):
- world rankings look fine
- national rankings look fine
- PRs look fine
- spot rankings (Portland Harbour) are still showing ghost speeds (e.g. 500m)
  - https://www.gps-speedsurfing.com/default.aspx?mnu=rankings&Year2=-&countryID2=268&SpotID2=681&Gender2=0&Tab=2&WeightClass2=0&AgeClass2=0&SpeedType2=3

gps-foilsurfing (Ben):
- rankings look fine
- PRs still contain ghost scores (e.g. 500m)
  - https://www.gps-foilsurfing.com/default.aspx?mnu=user&smnu=personalbest&uid=24525

**Comment by Logiqx** [comment]
I've added issue #21 which requests a Spot_Sessions method on the GP3S API.

This will allow the Python script that checks event rankings to also check spot rankings, highlighting ghost results, etc.

**Comment by Logiqx** [comment]
@jhdebruin - Aside from the Dunkerbeck event, only 3 events on GP3S still contain "ghost" rankings.

https://logiqx.github.io/gp3s-query/events/

- [2022 Spanish Speed Challenge](https://logiqx.github.io/gp3s-query/events/737.html) (2 users)
- [2022 DBO Speed Challenge](https://logiqx.github.io/gp3s-query/events/732.html) (3 users)
- [Singlis-Speedchallenge 2022](https://logiqx.github.io/gp3s-query/events/725.html) (1 user)

I suspect a rebuild of these events / users may well fix the problem.

**Comment by jhdebruin** [comment]
Check, will do some actions tomorrow or tonight, and let's we can fix them all

**Comment by Logiqx** [comment]
Worth noting that "ghost" rankings generally seem to have one of two confirmed possible causes:
- Sessions which have been deleted
- Sessions which have subsequently had the selected event cleared (either intentionally or unintentionally)

Another possible cause is the event being changed. I haven't stumbled across this scenario but it seems probable.

**Comment by jhdebruin** [comment]
Most likely the two options above, its not that easy to change an event afterwards.... don't think there is a menu option for that either

**Comment by Logiqx** [comment]
> Most likely the two options above, its not that easy to change an event afterwards.... don't think there is a menu option for that either

Bad phrasing on my part. What I meant is editing the session and selecting a different event.

**Comment by jhdebruin** [comment]
Fixed ->

spot rankings (Portland Harbour) are still showing ghost speeds (e.g. 500m)

https://www.gps-speedsurfing.com/default.aspx?mnu=rankings&Year2=-&countryID2=268&SpotID2=681&Gender2=0&Tab=2&WeightClass2=0&AgeClass2=0&SpeedType2=3

**Comment by jhdebruin** [comment]
Rebuild seems not to work for this one ->

https://www.gps-foilsurfing.com/default.aspx?mnu=user&val=327504&uid=24525 , will make an new issue for this

**Comment by Logiqx** [comment]
> Rebuild seems not to work for this one ->
> 
> https://www.gps-foilsurfing.com/default.aspx?mnu=user&val=327504&uid=24525 , will make an new issue for this

Makes sense. I can see this is issue #27.

I can also confirm the other issues have been fixed.
