### ISSUE TITLE
Extending an event

### ISSUE THREAD

**Issue by Mroosliir83** [djong1/gp3s#111]
Hope all is well. We would like to change the format of the Irish Speed Masters event to 1st of January to 31st of December going forward. 

At the moment we run it from the 1st of November to the 31st of October each year so that the end date coincides with the AGM and prize giving of the Irish Windsurfing Association. 

With this in mind, would it be possible to extend the end date of the 2022 Irish Speed Masters to finish on the 31st of December 2022? The event is closed so I can't change the date. https://www.gps-speedsurfing.com/default.aspx?mnu=event&val=717

I've already set-up the 2023 Irish Speed Masters to start on Jan1st to Dec 31st 2023

Kind regards

Marc Roosli

**Comment by djong1** [comment]
updated and ranking rebuild, so sessions posted after should be included
