### ISSUE TITLE
Incomplete list of event sessions

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#116]
I've noticed that a number of events are not reporting some of the sessions. A simple example might help in diagnosis:

Two people are listed in the rankings:

![image](https://user-images.githubusercontent.com/17449078/208161585-3193d955-b742-4624-af1f-e566d9e01f38.png)

One person is listed in the sessions:

![image](https://user-images.githubusercontent.com/17449078/208161615-21ec91fe-9439-461b-8f07-70c6975e616c.png)

This happens in a lot of events across all of the sites.

Where sessions are missing they are reported as "ghost" (or "invalid") rankings in my reports - https://logiqx.github.io/gp3s-query/

Once the sessions are listed in full, I'd be happy to run the reports again.

**Comment by djong1** [comment]
solved (bug in update routine for deleted sessions)
