### ISSUE TITLE
Merged tracks on map view

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#12]
A UK session (auto-posted by COROS) also shows someone’s runs from Sweden on the map:

[Simon Pettifer's track containing Swedish runs](https://www.gps-foilsurfing.com/default.aspx?mnu=user&val=388527&uid=4276&spotid=681)

The FIT has been exported by Simon (using the COROS app) and it does not include a Swedish track.
 
Suspect this is either a bug in the COROS backend or utilisation of the API during auto-upload to GP3S.

It should be noted that Simon's speeds are accurate so the session should NOT be deleted, only used for diagnosis.

**Comment by djong1** [comment]
Thanks for reporting, this is a bug in our mapping module. The external mapping provider does not return a session identifier and when running multiple jobs at the same time it may happen that multiple mapping job are combined in one map image. Solution is to run sequential (performance degradation) or have multiple mapping API's (recommended by provider) but Cost implication. I will investigate other solutions when I have time.

**Comment by djong1** [comment]
Backend Coros problem won't be fixed soon, on there roadmap
