### ISSUE TITLE
Neverending Uploads and stores sessions not appearing

### ISSUE THREAD

**Issue by maker962** [djong1/gp3s#121]
I am uploading tracks (.fit and .gpx) which do not complete. I click Refresh and they still show in progress. I logged off, then on' left for over a week and they are still there showing as in progress. When I click Upload Track to try again and enter file details it tries again and was showing one upload in my sessions, but when I click on MY Sessions nothing shows.
It seems to stuck in an process.

**Comment by jhdebruin** [comment]
Could you upload (or mail to info@gps-speedsurfing.com) the files you try to upload so we can do some checks

**Comment by maker962** [comment]
Just emailed 4 files.

**Comment by jhdebruin** [comment]
Caused by invalid tracks, containing SMART logging
