### ISSUE TITLE
Events ending early?

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#126]
Events ending on 31 Dec 2022 have now disappeared from the events list.

![image](https://user-images.githubusercontent.com/17449078/210129968-be2e9e58-df18-419c-a34e-d22e488a59f4.png)

This may be a more generic problem with events disappearing on the last day?

ISTR it happening with the British Speed Challenges back in October.

**Comment by Logiqx** [comment]
p.s. They don't appear in the "past events either", so they are neither "running" or "past".

![image](https://user-images.githubusercontent.com/17449078/210130024-0debd0c4-8216-4319-bdad-b72b5014a696.png)

**Comment by jhdebruin** [comment]
We changed this settings earlier in 2022, in the previous event admin screen this was a bit confusing, when the event ended at 31-12-2022,  you had to provide the date 1-1-2023, the new admin screen has now a more logical field for this, called end date. This should be solved for all new events

**Comment by Logiqx** [comment]
The events that disappeared from view today had an end date/time of 2022-12-31T00:00:00.

That date/time has now passed. However, events that remain all have the following end date/times:

- 2023-06-30T00:00:00
- 2023-09-30T00:00:00
- 2023-12-31T00:00:00

These are from the API and I suspect they are actual datetime fields from the database? If so then I'm 99.9% sure that all other events will do exactly the same thing at one minute past midnight on the end dates.

This issue certainly affects the visibility of the events on the website, perhaps also the calculation of rankings if the same logic is being used.

I think it would be well worth Dylan looking into this issue.

**Comment by djong1** [comment]
this was a cache problem, changed the renew date for the cache at midnight (was server restart time +24 hour)
