### ISSUE TITLE
British Speed Challenge 2023

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#128]
The British Speed Challenge is for sessions on UK waters, yet it includes a result from Diaz Point, Luderitz.

![image](https://user-images.githubusercontent.com/17449078/210130209-21221ad6-1dee-4b55-af71-17e5010a4739.png)

I'm not sure if "scope/area" has been defined incorrectly for the British Speed Challenge or if it is a bug?

**Comment by jhdebruin** [comment]
Please contact the event admin for this, most likely Jim Crossley has manual selected this event when uploading his session. It can be removed from the Event Admin module

**Comment by Logiqx** [comment]
Jim has selected the Dunkerbeck event so it's not caused by his selection.

I've messaged Simon to ask if the scope/area of the event is set to "country" (i.e. United Kingdom).

**Comment by djong1** [comment]
scope was indeed set to world, I have changed it to country.

**Comment by Logiqx** [comment]
Thanks. I'll notify Simon.
