### ISSUE TITLE
Green / yellow device indicator on session lists

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#13]
It would be useful if the lists of sessions could show the green / yellow icon like the rankings:

- [Latest Sessions](https://www.gps-foilsurfing.com/default.aspx?mnu=latestsessions)
- [Event Sessions](https://www.gps-foilsurfing.com/default.aspx?mnu=eventsessions&val=707)
- [User Sessions](https://www.gps-foilsurfing.com/default.aspx?mnu=user&smnu=sessions&uid=2640)

This will be helpful when trying to persuade people to use approved devices and when educating people not to do GPX exports from COROS devices to boost their speeds!

**Comment by djong1** [comment]
decided not to implement it since the UI will be overcrowded. In the long term we will move to a new design (wide Page) and that will make it possible. For now, we close this one as "won't fix".
