### ISSUE TITLE
Display full track & fastest runs not visible when uploading with .AOA files

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#130]
See for example this session -> https://www.gps-speedsurfing.com/default.aspx?mnu=user&val=400139&uid=22310 

- When selecting display track no track is visible 
- When selecting display runs no runs are visible

**Comment by WingMic** [comment]
Hoi Dylan, toevallig heb ik dit vanaf 1 december en hoop dat het lukt dit op te lossen. Mis deze data, lijkt alleen te gebeuren als ik post met de motion, met de coros zie je wel alles. Echter niet bij alle motions treed dit probleem op zie ik….?

**Comment by djong1** [comment]
It is fixed. Thanks for reporting
