### ISSUE TITLE
Evaluated ranking details page shows "No data found" for every distance

### ISSUE THREAD

**Issue by jschuitema** [djong1/gp3s#131]
For example see here:

https://www.gps-speedsurfing.com/default.aspx?mnu=user&eval=speed_avg&uid=6135&year=2023

Also added an image:

![Evaluated_no_data_found](https://user-images.githubusercontent.com/36237135/210979315-3aae7b21-3f9f-478f-b8fd-2cb7729f4955.png)

It is not the case for all riders:

https://www.gps-speedsurfing.com/default.aspx?mnu=user&eval=speed_avg&uid=1490&year=2023

but here the data seems outdated.

**Comment by jhdebruin** [comment]
Evaluated are processed once a week during the weekend, it all is ok this should be updated next monday

**Comment by djong1** [comment]
after a week it is updated
