### ISSUE TITLE
Event rankings and sessions gpskraaijchallenge

### ISSUE THREAD

**Issue by Erwinrovers** [djong1/gp3s#132]
hello
i have 3 events made for the gpskraaijchallenge
The event for gpsspeedsurfing is working fine .
But the events for foilsurfing and windfoiling not. 
By the 2023 2023 foilsurfing gpskraaijchallenge , only 1 person  is showing , in stead of more .
And the 2023 2023 wingsurfing gpskraaijchallenge event says no data , but there is already a session .

greetings

Erwin Rovers
www.Gpskraaijchallenge.nl

**Comment by djong1** [comment]
fixed, worker function was crashed

**Comment by Erwinrovers** [comment]
Thanks Dylan 

Nice evening 

Greetings

Erwin 

Verstuurd vanaf mijn iPhone

**Comment by djong1** [comment]
Event admin module is improved, you can now reset the ranking of a user and remove a user from the event. This is a Beta release and it would be nice if you can test. Deployment is done around 10 am this morning.

**Comment by Erwinrovers** [comment]
Bedankt Dylan 

Zag dat nog niet alles werkte .
Ik hou je op de hoogte 

Grt

Erwin 

Verstuurd vanaf mijn iPhone

**Comment by Erwinrovers** [comment]
hi dylan

Heb alleen nog een vraag , heb een posting van iemand , die geen event heeft toegevoegd ,aan zijn sessie ,
(hij staat wel aangemeld bij het event ) maar toch bij het event staat .
event : 2023 2023 wingfoiling gpskraaijchallenge .
persoon : frank heinen .

mvg

erwin rovers
________________________________
Van: Dylan de Jong ***@***.***>
Verzonden: woensdag 11 januari 2023 09:40
Aan: djong1/gp3s ***@***.***>
CC: Erwinrovers ***@***.***>; Author ***@***.***>
Onderwerp: Re: [djong1/gp3s] Event rankings and sessions gpskraaijchallenge (Issue #132)


Event admin module is improved, you can now reset the ranking of a user and remove a user from the event. This is a Beta release and it would be nice if you can test. Deployment is done around 10 am this morning.

**Comment by Erwinrovers** [comment]
hi dylan

i am missing the control page by  speedsurfing event 2023  gpskraaijchallenge    ,
want to erase  a wrong  session , but page  is not opening

greetings

erwin
