### ISSUE TITLE
Change "Delete Session" icon

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#135]
Change the "Delete Session" icon to more UI friendly version , current is red dot, advice to go for trash icon , see attachment ![image](https://user-images.githubusercontent.com/109060128/212747574-86db3f84-58b4-47e3-bc7d-28ce3795320f.png)

**Comment by jhdebruin** [comment]
![image](https://user-images.githubusercontent.com/109060128/212747989-f7ca6653-bc4f-4689-a508-c3f419e6bf8d.jpeg)

https://www.flaticon.com/free-icon/trash-can_542724

**Comment by djong1** [comment]
done
