### ISSUE TITLE
King of the Ice - event

### ISSUE THREAD

**Issue by ClaesKOTI** [djong1/gp3s#137]
Uploaded tracks doesent show in the event results. Example: Boris Lub...

Kind regards Claes![image](https://user-images.githubusercontent.com/122862086/212837227-0860c448-ddf1-4975-8750-6e8076fc8135.jpeg)

**Comment by jhdebruin** [comment]
Did a rebuild of the event ranking, session of Boris now included. Please verify if all ok now @ClaesKOTI

**Comment by ClaesKOTI** [comment]
Thanks Jan Hendrik, now We have Tobias Bodin in the chart as well. Many
Thanks for your prompt feedback on this. Kind regards Claes

tis 17 jan. 2023 kl. 14:17 skrev Jan Hendrik de Bruin <
***@***.***>:

**Comment by jhdebruin** [comment]
Great, will close it for now, if new issues occur please open a new GitHub issue for this

**Comment by ClaesKOTI** [comment]
Will do, thanks!

tis 17 jan. 2023 kl. 15:07 skrev Jan Hendrik de Bruin <
***@***.***>:
