### ISSUE TITLE
GPS-Wingfoiling API not returning data - 401 Unauthorized

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#139]
This started out with me thinking the GPS-KiteSurfing API was not returning event sessions.

I initially noticed this when running my reports but the API "try it" page also had an issue:

![image](https://user-images.githubusercontent.com/17449078/212844998-d9d00fe1-221b-4a91-9f24-24ad47d7273b.png)

![image](https://user-images.githubusercontent.com/17449078/212845072-57a03566-eee2-440f-91c7-cfc0b59acd76.png)

**Comment by Logiqx** [comment]
Update. I seem unable to retrieve the following:

- gps-kite - event sessions
- gps-wing - event rankings + event sessions

Everything else appears to be working.

**Comment by jhdebruin** [comment]
Remark for @djong1 , there are no actual events running at Kite at this moment, could be related....

**Comment by Logiqx** [comment]
> Remark for @djong1 , there are no actual events running at Kite at this moment, could be related....

Ah, that's my bad regarding gps-kite. It would appear my code needs a tweak to handle this scenario.

**Comment by Logiqx** [comment]
Ok, I've fixed the bug in my code.

My code scrapes the event list from the website and in the absence of current events it was using the past events.

Fixed now.

**Comment by Logiqx** [comment]
I've confirmed the issue with the wing API - "401 Unauthorized"

My subscription seems ok so I'm guessing it's the permissions on the individual operations.

![image](https://user-images.githubusercontent.com/17449078/212877541-6d15830e-ecb1-433d-8816-8bbe8f626e29.png)

**Comment by djong1** [comment]
fixed, app registration for wing was expired and not automatically renewed due to a bad config

**Comment by Logiqx** [comment]
Thanks. Confirmed as working.
