### ISSUE TITLE
Session disappeared from Event ranking after editing

### ISSUE THREAD

**Issue by dgpro** [djong1/gp3s#141]
After uploading a [new session](https://www.gps-wingfoiling.com/default.aspx?mnu=user&val=400983&uid=24191) to the [2022 British Wingfoil Challenge 2023](https://www.gps-wingfoiling.com/default.aspx?mnu=event&val=759) I noticed that only my [previous session](https://www.gps-wingfoiling.com/default.aspx?mnu=user&val=400491&uid=24191) was in Event's ranking (even after a couple of days). So I removed Event from my older session and my last session appeared in rankings as expected but when I filtered it by "Speed Type: Max 2 sec" it wasn't in the results for some reason...
So I removed Event from my last session as well and then added it back which made things worse. My session just disappeared from Event ranking permanently (with any filter) no matter how many times I updated it with correct event.
But I managed to fix it by removing Event completely from [My Events](https://www.gps-wingfoiling.com/mygps.aspx?mnu=events) and subscribe back to it again and update the session.

I hope it helps someone with similar problem but it's a bit frustrating.

**Comment by jhdebruin** [comment]
Hi, next time please report it here before reposting, we have some admin features for event to fix this pretty easy, lets see if that helps next time
