### ISSUE TITLE
Cannot add items.

### ISSUE THREAD

**Issue by boardsurfer** [djong1/gp3s#145]
I cannot add a board or a fin, because the site does not show a list of available boards/fins.

![image](https://user-images.githubusercontent.com/20163848/213783957-f3330e4c-c646-4619-8686-e1053add28a5.png)
![image](https://user-images.githubusercontent.com/20163848/213784097-04e6056c-91cb-42da-91a3-34da79057a00.png)

**Comment by djong1** [comment]
Please select a board brand first and second click GO
