### ISSUE TITLE
Can't choose Event 

### ISSUE THREAD

**Issue by HannesRieger** [djong1/gp3s#147]
Since a week or so I can't choose the event when posting a Session 
![Screenshot_2023-01-29-19-32-45-287_com android chrome](https://user-images.githubusercontent.com/123925981/215399508-8f0ce1b6-9fab-4904-b50c-19d67c919b0b.jpg)
![Screenshot_2023-01-29-19-33-11-583_com android chrome](https://user-images.githubusercontent.com/123925981/215399530-cafbbc52-cdfc-4c5a-a250-77ef1d3cc176.jpg)

Is it only me or are others affected as well?

**Comment by jhdebruin** [comment]
Thats no longer needed, once subscribed for any event it will be added to all the active events that matches the criteria automatic….

**Comment by HannesRieger** [comment]
My Session is not added to the event 😩

**Comment by HannesRieger** [comment]
Took some time, now it is added. Thanks!

**Comment by jhdebruin** [comment]
If i see correctly event starts today, so first sessions are sailed this afternoon ? @liutgied

**Comment by liutgied** [comment]
Correct - to be honest correct time is 12:00 today - day is inclusive. And it finished Friday evening 17:00. I am not concerned about exact time on Friday, because anyway it is dark at that time :)

**Comment by jhdebruin** [comment]
Ok, will try to look at this tonight to see what's the reason why the sessions (only three now ) are not listed

**Comment by liutgied** [comment]
I see more and more participants added their sessions, but seems like only one is added

**Comment by jhdebruin** [comment]
> I see more and more participants added their sessions, but seems like only one is added

Just did a rebuild on -> https://www.gps-icesailing.com/default.aspx?mnu=eventranking&val=789 , could you verify if ok now ?? @liutgied

**Comment by liutgied** [comment]
And one more missing: https://www.gps-icesailing.com/default.aspx?mnu=user&val=401369&uid=26046&spotid=18101

**Comment by jhdebruin** [comment]
Thnx for reporting @liutgied , looks there something with the rank builder, to be continued :)

**Comment by liutgied** [comment]
Thank you for the support - one more question - can I somehow analyse or in the worse case get tracks or get some info form the tracks? There is this issue - that officially it is from 12:00 - some guys posted sessions which started earlier. Ideally - I wanna just cut the tracks to start from 12:00. I am from IT as well - so I know gpx is XML and in the worse case it is possible  for me to get those files and curt it to 12:00 and reupload... But if somehow differently I could do it automatically would be great

**Comment by jhdebruin** [comment]
@liutgied This not possible at the website, you could do this with GPS Results, just add the timeframe and export the track with the correct timeframes ( https://www.gps-speed.com/download_e.html )

**Comment by liutgied** [comment]
[jhdebruin](https://github.com/jhdebruin) - ok. But can I get tracks from guys who posted on my event? I don't wanna ask everyone personally the track and check it... And/or at least see the start of the track (so I know whom to ask).
Thanks

**Comment by jhdebruin** [comment]
thats the only way to do this....  we don not share individual tracks

**Comment by liutgied** [comment]
ok - I can ask the guys to give me tracks - but could you say or can I find somewhere the list of starting time of tracks. I just need  the list of guys/tracks which started before 12:00, Monday January 30.
Thank you

**Comment by jhdebruin** [comment]
As a premium member you could use this view

![image](https://user-images.githubusercontent.com/109060128/215852223-75319465-a12c-42dd-a0b4-ae4ac7f72240.png)

But keep in mind that times could differ due timezone / lightsaving settings etc etc 

think we should close this discussion here, not to polute the original issue....

**Comment by Erwinrovers** [comment]
hi am still having  problems , i download the  files as excel files , en then upload them to our site (www.gpskraaijchallenge.nl)
but up  to last  week it worked fine , but  since  the automation of  the events not any more  .
i tried today again a test  session , but i didn,t  work .

greetings  erwin
