### ISSUE TITLE
Excel export from Event Module doesn't show every session 

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#152]
hi am still having  problems , i download the  files as excel files , en then upload them to our site (www.gpskraaijchallenge.nl)
but up  to last  week it worked fine , but  since  the automation of  the events not any more  .
i tried today again a test  session , but i didn,t  work .
Can  you help us ?

greetings  erwin

_Originally posted by @Erwinrovers in https://github.com/djong1/gp3s/issues/147#issuecomment-1414250057_

**Comment by djong1** [comment]
should be fixed

**Comment by Erwinrovers** [comment]
hello gpsspeedsurfing crew
Many thanks for the good service and help  .
its working  fine again .

greetings 

the gpskraaijchallenge crew

erwin and menno
