### ISSUE TITLE
Convert the Netherlands Antilles into Curacao, Bonaire and St. Maarten

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#157]
I recently got a (free) account on the gps speedsurfing site. And since last weekend I've been posting my sessions with my new Coros watch.
Now I wonder if you can convert the Netherlands Antilles into Curacao, Bonaire and St. Maarten.
Since 2010 the Netherlands Antilles no longer exist and I would like to see a Curacao flag next to my name if possible.

**Comment by djong1** [comment]
I have added these countries and flags. I have also regrouped the spots, a couple are still open and would be great if you can help with pointing out the right country: 

- Sorobon
- Pink Beach
- Te Amo Beach
- Fischermans Hut
- Vista Blue

**Comment by djong1** [comment]
@jhdebruin any updates from the rider who requested this?

**Comment by jhdebruin** [comment]
@djong1 Yes....

_Sorobon (Lac), Pink Beach, Te Amo Beach en Vista Blue zijn op Bonaire.

Fisherman's Hut is op Aruba


Tim_

**Comment by vierfuffzig** [comment]
@djong1 
imho `Bonaire, Sint Eustatius Saba -> Lac Bay Bonaire` is the most frequently and recently used of all four `lac bay` instances.

there's a doublette right there just without the `bonaire` in the spot name:
![image](https://user-images.githubusercontent.com/9342253/234842814-a38e0036-4677-4f15-beb6-c27e2f216ba7.png)

a third instance under `netherlands`
![image](https://user-images.githubusercontent.com/9342253/234842358-3ab7eb7e-78fc-4baa-9543-c9c74b69c8e2.png)

and a fourth one called `sorobon` under `netherlands antilles` (sorobon is the headland into lac bay where all windsurf-related infrastructure is situated)
![image](https://user-images.githubusercontent.com/9342253/234843884-726faada-6ab4-42db-a502-0521248091aa.png)

additionally, we don't find the other bonairian spots `te amo`, `vista blue` and `pink beach` (likely the most speeds-relevant spot on bonaire, see taty's session) under `bonaire sint eustatius saba` , but under `netherlands antilles` instead, which (in a geopolitical sense) stopped existing 13 yeras ago.

what i'd suggest (if technically possible) is:
- merge everything lac bay + sorobon into `bonaire sint eustatius saba -> lac bay bonaire` and remove the remaining three redundant spot intances
- merge `pink beach` and `pink beach bonaire` and move it from `netherlands antilles` to `bonaire st eustatius saba`
- merge `fishermans hut` from` netherlands antilles` into its `aruba` pendant
- remove `netherlands antilles` as a country option
- try to motivate people to look up existing spot options before creating doublettes ;)

thanks for making this platform happen,
cheers, basti.

**Comment by djong1** [comment]
Thanks, done
