### ISSUE TITLE
API - Several speed types missing from Event_Sessions

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#16]
Whilst using the API, I noticed that a number of the speed types are absent in Event_Sessions and User_Sessions.

- speed_24hour
- speed_alpha_racing
- speed_foil
- speed_formula
- speed_halfhour

speed_alpha_racing and speed_halfhour are potentially the most interesting of these speed types.

If the missing speed types can be added to the Event_Sessions output it would be quite useful.

**Comment by Logiqx** [comment]
Worth noting that these additions will be particularly useful to my Python script for checking event rankings.

https://github.com/Logiqx/gp3s-query

Currently, it can't check these 5 speed types without them being in the Event_Sessions.

**Comment by djong1** [comment]
I would like to take the opportunity to improve the API in a later time-frame and add this request to the V2 API

**Comment by Logiqx** [comment]
That's fair enough.

I've just noticed that these fields are also absent from User_Sessions so I'll update the first comment.

Hopefully there aren't too many speed_alpha_racing and speed_halfhour errors in the event rankings.

**Comment by djong1** [comment]
@Logiqx we have released a beta version of the API: gps-speedsurfing-api-v2

Changed Ranking and sessions, don't use spotranking yet.

        added speed fields in rankings:
        
        - speed_24hour
        - speed_alpha_racing
        - speed_halfhour
        
        These speed types will not be added:
        - speed_foil
        - speed_formula

Added speed types in sessions, is inline with rankings
Shows now complete set of sessions to be in-line with the latest event module update

The api parameter path changed a bit,

please comment @Logiqx

**Comment by Logiqx** [comment]
@djong1 

I'm having trouble with event sessions. Maybe the service docs aren't quite right?

![image](https://user-images.githubusercontent.com/17449078/185222614-40ec377d-ea67-4d74-be92-13d45ac8b5a5.png)

**Comment by djong1** [comment]
@Logiqx is fixed now, but I need to add pagination to overcome timeout issues for huge event lists

**Comment by Logiqx** [comment]
@djong1 A few things to address:

- sessionurl is missing "uid="
- session_date has changed format from "2021-10-02T00:00:00" to "10/2/2021 12:00:00 AM"
- getting list of sessions is really slow. Suggest you look consider the schema design, especially suitable indices.

I've re-run the reports which now list a lot of issues.

https://logiqx.github.io/gp3s-query/events/

I've only checked a few things but they seem legit errors.

e.g. https://logiqx.github.io/gp3s-query/events/726.html - Robert Baas is missing from the rankings

**Comment by djong1** [comment]
sessionurl = fixed
performance is fixed

please confirm that this works, this update apply's only for the events hosted in 2022. When this approach works we will apply it to the older events also. Can you also run a new matching run?

**Comment by Logiqx** [comment]
@djong1 

Thanks, looking better now - https://logiqx.github.io/gp3s-query/events/

3 events with lots of "ghosts" are showing zero sessions, despite having rankings:
- Zuidlaardermeer Speed Challenge 2022 (730)
- FFF SPEED CHALLENGE (727)
- Lysakerfjorden 2022 (722)

I'll let you work your way through the other errors being reported.

Can you use a standard format for session_date in event sessions please?

**Comment by djong1** [comment]
closed, api updated
