### ISSUE TITLE
Deleting   a session at a event ?

### ISSUE THREAD

**Issue by Erwinrovers** [djong1/gp3s#160]

**Comment by Erwinrovers** [comment]
Hi , before i could as a admin delete a single ession .
but i see the  option is away ?
one of our eventsurfers , surft somewhere else, but our event  is attached at his session .
You can also not edit  a session for removing the  event  know .
session  :[ ](https://www.gps-speedsurfing.com/default.aspx?mnu=user&val=400413&uid=26026)

greetings

erwin

**Comment by djong1** [comment]
Please provide link to session

**Comment by Erwinrovers** [comment]
https://www.gps-speedsurfing.com/default.aspx?mnu=user&val=400413&uid=26026

**Comment by Erwinrovers** [comment]
https://www.gps-speedsurfing.com/default.aspx?mnu=user&val=402518&uid=4524

deze ook volgens mij
![Uploading Schermafbeelding 2023-02-21 om 17.00.56.png…]()

**Comment by Erwinrovers** [comment]
<img width="837" alt="Schermafbeelding 2023-02-21 om 17 00 56" src="https://user-images.githubusercontent.com/122383988/220396821-52b2301f-a8a1-4973-bc50-5c9161627ba1.png">

**Comment by djong1** [comment]
Je kan de ranking voor een user rebuilden in de admin module - selecteer user en dan rebuild. Ik heb het getest voor je event en het werkt

**Comment by Erwinrovers** [comment]
thanks for the  service 

greetings

the  KraaijchallengeCrew
