### ISSUE TITLE
Sessions with new Coros devices don"t show the "green" doppler icon

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#164]
Sessions posted with a new Coros Apex 2 and uploaded with the auto-uploader don't show the right "green" doppler icon in the sessions details.

**Comment by djong1** [comment]
do you have an example session, please share the link. Sessions posted with GPX upload are shown in yellow.

**Comment by jhdebruin** [comment]
https://www.gps-speedsurfing.com/default.aspx?mnu=user&val=403120&uid=695


Auto-sync is used

**Comment by djong1** [comment]
solved
