### ISSUE TITLE
f

### ISSUE THREAD

**Issue by raymond-w** [djong1/gp3s#166]
When opening the page is shows a "f" between the nav bar and the logo

**Comment by djong1** [comment]
which page, can you share a link=

**Comment by jhdebruin** [comment]
<img width="346" alt="Screenshot 2023-03-25 at 22 48 31" src="https://user-images.githubusercontent.com/109060128/227743863-508e559a-e9a9-4fd8-b220-9879cbb95318.png">

**Comment by djong1** [comment]
solved, pushed with next build. Thanks for reporting and your patience
