### ISSUE TITLE
Missing sessions on the Odyssey of Speed

### ISSUE THREAD

**Issue by timotte0909** [djong1/gp3s#17]
while checking the ranking of the Odyssey of Speed it appears that for a certain period of time some sessions are not considered, and even wrong one show up. 

So the fastest session of Twan Verseput are missing, instead a eession fron Fuerte is showing up.
it seems that for the period from 20/07 and 25/07 is impacted.

**Comment by jhdebruin** [comment]
Hi @timotte0909 , i've done a manually rebuild of the event entries, could you please check if its ok now ?

**Comment by Logiqx** [comment]
@jhdebruin my script now says "No users need a rebuild in 2022 Odyssey of Speed (736)" so I think your manual rebuild has worked.

As with the ticket #14 the weighted ranking may also need attention.

**Comment by timotte0909** [comment]
looks ok, again. Thanks a lot!

**Comment by Logiqx** [comment]
Ahh... broken again.

Issues identified: https://logiqx.github.io/gp3s-query/events/736.html
