### ISSUE TITLE
Errors in event rankings

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#171]
Sorry to be the bearer of bad news but errors have returned in the event rankings:

https://logiqx.github.io/gp3s-query/gps-speed/events/

I last ran the script at the end of January so these errors have appeared in the last two months.

n.b. Errors reported in the "Spanish Challenge" are only apparent when viewing the actual speeds in km/h. They reports show they are the same in knots but nevertheless an inconsistency. This had me a little confused, until I stepped through the script to see the session and rankings do indeed contain different speeds.

**Comment by jhdebruin** [comment]
Thnx, will discuss this with @djong1  first before fixing....

**Comment by djong1** [comment]
I made a change in concurrent processing logic and I wonder if it looks better now, not all will be solved, but occurrences should be less I hope.

**Comment by jhdebruin** [comment]
@Logiqx @djong1 I've rebuild all the event rankings with issues, @Logiqx could you run the script again just to check if there are any new / open errors ?

**Comment by Logiqx** [comment]
It looks better than before. A few duplicates and a few missing.

For some reason, I can't push changes to GitHub right now so here are screenshots of the latest:

![image](https://user-images.githubusercontent.com/17449078/232254420-c2f9f6a0-f828-478a-9878-3944f7f40e53.png)

![image](https://user-images.githubusercontent.com/17449078/232254432-295a3945-b95a-4411-8f57-9b74594e8824.png)

![image](https://user-images.githubusercontent.com/17449078/232254469-8c1015d1-6340-42e0-ade7-3ecaaf0b06f2.png)

**Comment by Logiqx** [comment]
Reports online:

https://logiqx.github.io/gp3s-query/

**Comment by jhdebruin** [comment]
Thnx @Logiqx

**Comment by djong1** [comment]
@jhdebruin can you fix the outstanding errors with rebuild for these users?

**Comment by jhdebruin** [comment]
Already did @djong1
