### ISSUE TITLE
Event / deleted Users will be shown in ranking and sessions

### ISSUE THREAD

**Issue by blinki-bill** [djong1/gp3s#176]
Hey gp3s Team,
in the event https://www.gps-speedsurfing.com/default.aspx?mnu=event&val=769 i delete some Users because they wont fulfil the NOR. 
The Tracks from the deleted users will still be shown now in Ranking and Sessions.
The Sessions are: 
https://www.gps-speedsurfing.com/default.aspx?mnu=user&val=401139&uid=24518&spotid=18034
https://www.gps-speedsurfing.com/default.aspx?mnu=user&val=400310&uid=25106&spotid=18034

I was sure the sessions wont be scored after updating with this ticket:
https://github.com/djong1/gp3s/issues/108#event-8333446300

Sorry for making work for you.

kind regards
Werner

**Comment by jhdebruin** [comment]
Hi @blinki-bill , i forced a rebuild of the event ranking, could you check if ok now ?
