### ISSUE TITLE
change board name ?

### ISSUE THREAD

**Issue by Erwinrovers** [djong1/gp3s#177]
is it possible to change a board name by equipment  ?

i  have this one :

JP | Slalom Pro Edison | 68 x 232 cm | 105 l | 2019 | Speed/Slalom Small
-- | -- | -- | -- | -- | --

if it  is possible ,to change -slalom pro edison to :  slalom 68 pro edition

**Comment by jhdebruin** [comment]
Not yet possible,  we will investigate of this is a feature we can build in near future

**Comment by Erwinrovers** [comment]
thanks  anyway  

greetings

erwin

**Comment by djong1** [comment]
This is possible. Go to My boards select the name and year and click the "pen/edit" icon on the right:
<img width="673" alt="image" src="https://user-images.githubusercontent.com/25177991/234785404-c7409bbb-cdee-4524-848d-b19b16885df2.png">
