### ISSUE TITLE
foilsurfing event ranking 

### ISSUE THREAD

**Issue by Erwinrovers** [djong1/gp3s#178]
i have only 1 person in the event ranking , in stead  of 5  ,
do i have  to rebuild the  other users ?[
[
](https://www.gps-foilsurfing.com/default.aspx?mnu=eventranking&val=781)
greetings

erwin rovers
2023 foilsurfing gpskraaijchallenge

**Comment by jhdebruin** [comment]
I've done a rebuild of the Event
