### ISSUE TITLE
rebuilding   users

### ISSUE THREAD

**Issue by Erwinrovers** [djong1/gp3s#179]
goodday

i have some issues wit our event , 2023  gpskraaijchallenge  .
i have  rebuid mulitple users , , for missing  sessions .
but now , i cant acces the  event .
can  you  rebuild  the event ?
or  make a option for complete rebuild   ?

greetings

erwin  rovers

**Comment by jhdebruin** [comment]
Have done a rebuild, i only see 3 riders now..... that's correct ? @Erwinrovers

**Comment by Erwinrovers** [comment]
the  event is gone ?
was like 12 riders 
speedsurfing - 2023 gpskraaijchallenge

grt

erwin

**Comment by jhdebruin** [comment]
I dont see it either, did a rebuild of the foilevent, are you sure you did not delete it by accident? There are no processes running at
our side to delete or remove events ,  we have to check the logs to see whats
up

**Comment by jhdebruin** [comment]
Event is still accessible by https://www.gps-speedsurfing.com/default.aspx?mnu=event&val=777

Can you check if this is the right one also with the correct sessions ? @Erwinrovers

**Comment by Erwinrovers** [comment]
No I only rebuild another user

🙈😢

Verstuurd vanaf mijn iPhone

Op 21 apr. 2023 om 07:07 heeft Jan Hendrik de Bruin ***@***.***> het volgende geschreven:

﻿

Event is still accessible by https://www.gps-speedsurfing.com/default.aspx?mnu=event&val=777

Can you check if this is the right one also with the correct sessions ? @Erwinrovers<https://github.com/Erwinrovers>

**Comment by jhdebruin** [comment]
@djong1 Could you please status of this event ( id = 777 ) and check logs what went wrong ? Data is still there but event not visible

**Comment by Erwinrovers** [comment]
yes its the right  one ,
but like you said ,  no sessions   or other data visible ?\


greetings

erwin

**Comment by djong1** [comment]
@Erwinrovers, unfortunately the event is deleted via a user action. It is a hard delete. I have made it a soft delete now to prevent users from making a mistake. 
 You can recreate the event yourself and if you know the subscribers we can re-create the rankings. Other option is to do a DB restore and transfer the data, but this will take me a lot of time. If re-creation is possible for you it has my preference.

**Comment by Erwinrovers** [comment]
hi i can recreate it , i know the subscribers .
can make a list .

greetings

erwin

**Comment by djong1** [comment]
please sent the list to info@gps-speedsurfing.com

**Comment by Erwinrovers** [comment]
done

**Comment by djong1** [comment]
done

**Comment by Erwinrovers** [comment]
thanks  for the effort ,
but can you replace bart de vries with bas de vries .

many thanks


erwin rovers
www.gpskraaijchallenge.nl<http://www.gpskraaijchallenge.nl>

________________________________
Van: Dylan de Jong ***@***.***>
Verzonden: vrijdag 5 mei 2023 14:40
Aan: djong1/gp3s ***@***.***>
CC: Erwinrovers ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [djong1/gp3s] rebuilding users (Issue #179)


Closed #179<https://github.com/djong1/gp3s/issues/179> as completed.

**Comment by Erwinrovers** [comment]
hoi dylan

Ik denk dat je er nog niet aan  toe bent gekomen ,
ben heel blij met je  inzet  , zult er ook wel druk mee hebben
maar zou je aub bart de vries met bas de vries willen ruilen in ons event aub

zeer bedankt alvast

erwin rovers

www.gpskraaijchallenge.nl<http://www.gpskraaijchallenge.nl>
https://www.gps-speedsurfing.com/default.aspx?mnu=event&val=825


________________________________
Van: erwin rovers ***@***.***>
Verzonden: vrijdag 5 mei 2023 15:12
Aan: djong1/gp3s ***@***.***>
Onderwerp: Re: [djong1/gp3s] rebuilding users (Issue #179)

thanks  for the effort ,
but can you replace bart de vries with bas de vries .

many thanks


erwin rovers
www.gpskraaijchallenge.nl<http://www.gpskraaijchallenge.nl>

________________________________
Van: Dylan de Jong ***@***.***>
Verzonden: vrijdag 5 mei 2023 14:40
Aan: djong1/gp3s ***@***.***>
CC: Erwinrovers ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [djong1/gp3s] rebuilding users (Issue #179)


Closed #179<https://github.com/djong1/gp3s/issues/179> as completed.
