### ISSUE TITLE
Script to Rebuild in 2022 Dunkerbeck Speed Challenge “The Summer Edition” (748)

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#18]
Based on the very handy python script from @logiqx this entries have to be rebuild in the event 748, @djong1  could you please make a small script for this ? All other events have been rebuild manually already :) 

44 / 439 users need a rebuild in 2022 Dunkerbeck Speed Challenge “The Summer Edition” (748):
Kai Kaufmann (16746) - speed_250, speed_500, speed_100, speed_10sec, speed_mile, speed_avg
Christopher Tyack (22404) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Tor Kjell Grytnes  (22817) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Konstantinos Palogos (23998) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Jorgen Dyblie (23206) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Torbjörn Hellström (23334) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Kristian Grytnes (23632) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_avg
Will Trossell (2911) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Sven Hulst (23299) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Pavlos Kapsianis (24816) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Jorrit Bonnema (22388) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Markus Lindman (5423) - speed_250, speed_500, speed_2sec, speed_100, speed_10sec, speed_avg
Marco Düwell (26365) - speed_250, speed_500, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Ingolf van Oostveen (3874) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Bert Bodde (20514) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Alwin Visker (15697) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Mandy van de Hoef (23463) - speed_250, speed_2sec, speed_100, speed_10sec, speed_avg
Ove Jansson (4642) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Alberto Marugan (25183) - speed_250, speed_500, speed_2sec, speed_100, speed_10sec, speed_avg
Chris Platt (25193) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
René Bijmolt (21711) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_avg
Jüri Kaldoja (4497) - speed_250, speed_500, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Fons van den Hove (24311) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Phil Noden (2708) - speed_250, speed_500, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Olsson Orjan (18230) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Frank Heinen (82) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Tore Hvideberg (25617) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Nicole Skodda (6348) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_avg
Lianne Hofstee (26179) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_avg
Hans Prins (5376) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Magnus Bengtsson (2046) - speed_250, speed_500, speed_hour, speed_100, speed_10sec, speed_avg
Anders Bjorkqvist (2558) - speed_mile, speed_hour, speed_avg
Dylan de Jong (53) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_avg
Arne Noer (24403) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Edwin Buruma (23550) - speed_250, speed_hour, speed_2sec, speed_100, speed_10sec, speed_avg
Peter L Rasmussen (26059) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Robert Baas (19409) - speed_250, speed_500, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Thomas Moldenhauer (24163) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Hans Kreisel (2042) - speed_250, speed_500, speed_hour, speed_100, speed_10sec, speed_mile, speed_avg
Regis Lesieur (22394) - speed_250, speed_500, speed_hour, speed_2sec, speed_100, speed_10sec, speed_avg
Deyan Gospodinov (26011) - speed_250, speed_500, speed_2sec, speed_100, speed_10sec, speed_mile, speed_avg
Hannes Rieger (24349) - speed_250, speed_2sec, speed_100, speed_10sec, speed_mile
Saar Schuling  (25189) - speed_mile, speed_hour
Mateusz Kasprzak (25524) - speed_hour

**Comment by Logiqx** [comment]
Prettier report now hosted on GitHub - https://logiqx.github.io/gp3s-query/events/748.html

**Comment by djong1** [comment]
@Logiqx please advise. You have created a great script to discover mismatches however I do need some additional help to understand what is wrong in the ranking:  

- the oddesey of speed was fine yesterday and based on the script it tells me that the rider speeds of Johnny Tuijn (AVG) are not correct now. However, when I go to the event and match his result on AVG with the fastest session in his session list I see no differences or mismatches. What do I overlook.?

Eventranking:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/25177991/183243360-c3e303d1-9956-483d-8392-ed9f56c0c7d3.png">
Rider session:
<img width="433" alt="image" src="https://user-images.githubusercontent.com/25177991/183243392-ba29b42c-1fc5-4d10-a9d2-94c72138b8d6.png">
Rider sessions:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/25177991/183243421-43f7df84-58d3-4147-8598-7c62c5789b02.png">



- session: https://www.gps-speedsurfing.com/default.aspx?mnu=user&val=386005&uid=2503
-

**Comment by Logiqx** [comment]
@djong1 - After re-running my reports the problem has now disappeared as the rankings have been updated.

I received the session details from the API around 5 hours ago but the rankings (main website and API) only updated within the past hour.

Either the rankings updated automatically or maybe @jhdebruin did a manual fix in response to my comment on #17.

**Comment by jhdebruin** [comment]
sorry for the disturbance, i actually did a manual rebuild for this one less than an hour ago 🙃 but was disturbed and forgot to comment this

**Comment by Logiqx** [comment]
@jhdebruin Thanks for clarifying. Good to have an explanation as opposed to it being a mystery!

Something worth bearing in mind with my script is that immediatley after a session has been posted (but prior to the rankings being updated) , my script has the potential to report a discrepency, if I just happen to run it at that time.

I might enhance the script to ignore newly discovered sessions (up to 1 hour after first discovery) to avoid this scenario.

**Comment by djong1** [comment]
@Logiqx Jan hendrik confirmed that he did not rebuild the Dunki event, however I see the same thing:

<img width="581" alt="image" src="https://user-images.githubusercontent.com/25177991/183248195-6d04a1e3-44a6-44f9-8d8e-7543cfe3546f.png">

<img width="419" alt="image" src="https://user-images.githubusercontent.com/25177991/183248224-8588a8c3-8327-44ab-8e99-953002904175.png">

**Comment by Logiqx** [comment]
That session is not associated with the Dunkerbeck event.

![image](https://user-images.githubusercontent.com/17449078/183253807-8c9280f4-5309-4262-9751-865f5604db2d.png)

I've now improved the message to say "These rankings do not have a session associated with the event.".

**Comment by djong1** [comment]
To give you a bit more insight: we are currently in the transition from 1 to 1 relations between session and event to 1 to many. To give users the opportunity to attach the session to multiple events. We do this first for the events rankings and for events that run on global or country level. We do that in coexistence to slowly transition (in a controlled manner) towards this new model. In the end: the event name will be removed from the session detail page, once a user is subscribed to an event his session will be automatically added to the event, the event selection will be removed from the  add session page when posting. 

This change will also affect the api in the end. We use a newer api version already for the web front end and when fully transitioned we will enable this one also for external use. We need some internal api operations during the coexistence phase. 

So my concern is that with this change we do not introduce new problems and make sure that old bugs are removed before transitioning. So your help is very valuable. Your data sparked also an idea to change the architecture a bit to overcome these issues by design. But first things first.

**Comment by Logiqx** [comment]
> To give you a bit more insight: we are currently in the transition from 1 to 1 relations between session and event to 1 to many
> ...
> Your data sparked also an idea to change the architecture a bit to overcome these issues by design. But first things first.

Cool. Thanks for the insight.

**Comment by jhdebruin** [comment]
@Logiqx  I've done a rebuild of the Dunkerbeck Event,  if all is ok we can close this issue...

**Comment by Logiqx** [comment]
Getting closer!

- DSC has improved a lot. 2 user rebuilds outstanding.
- I've implemented the date check. It now ignores some "non-issues" (sessions outside of the event dates):
  - 2022 Gps Kraaij Challenge is now clean
- The script has found the following **new** issues because sessions outside of the event period are being used for rankings:
  - SSS Go big or go Home 2021-2022
  - 2021 Red Bull Bora Challenge
  - Surf like a dude 2021 have issues.

![image](https://user-images.githubusercontent.com/17449078/183313608-23e94c0d-799f-47de-90bb-c792771a81ca.png)

**Comment by jhdebruin** [comment]
This specific action is closed, new open issues will be collected in #15
