### ISSUE TITLE
Session Upload Problem

### ISSUE THREAD

**Issue by MatthiasMahnke** [djong1/gp3s#181]
Hi Team GPS Speedsurfing,
try to upload my sessions since a couple of days but it is not working anymore.
Do you have an idea what could be the problem? 
Best regards 
Matthias

**Comment by jhdebruin** [comment]
Could you provide some more info : Error messages, Screenshot and share track thats causing the issue, thnx in advance @MatthiasMahnke !

**Comment by MatthiasMahnke** [comment]
How can I send it to you? Do you have an email address?

**Comment by jhdebruin** [comment]
You can upload it here or forward to info@gps-speedsurfing.com

**Comment by MatthiasMahnke** [comment]
Am not so familar with this platform, sorry. I have send screenshots and tracks by email. Thanks for your help!
