### ISSUE TITLE
British Speed Challenge ( windfoil ) 

### ISSUE THREAD

**Issue by simonchippa** [djong1/gp3s#183]
I’ve just noticed on British Windfoil speed challenge, we’ve got people subscribed to the challenge. 
but on the upload section, average speeds all that’s on the page is ‘no data’ 
Can we look into this . 
I’ll add screen shots below 
![A4D78BEE-173F-49E6-8735-BA508D2F6E18](https://user-images.githubusercontent.com/131901367/234647519-8707be83-ba25-4eca-a0d4-dd98d4fccdec.png)
![541FC63F-6A5D-472B-98F9-A52EC76A2BF9](https://user-images.githubusercontent.com/131901367/234647527-344b9641-0874-4d7e-ad38-a64b52937d15.png)
![D5D5B1D3-5693-4E14-874F-BD1239612356](https://user-images.githubusercontent.com/131901367/234647531-74358307-4166-4f30-9f01-d0b9896405f6.png)

**Comment by jhdebruin** [comment]
We did a rebuild of the event, please confirm if ok now @simonchippa

**Comment by simonchippa** [comment]
Thank you

All is perfect
Thankyou
Simon chippington GBR984

Sent from my iPhone

On 26 Apr 2023, at 23:17, Jan Hendrik de Bruin ***@***.***> wrote:

﻿

We did a rebuild of the event, please confirm if ok now @simonchippa<https://github.com/simonchippa>
