### ISSUE TITLE
Super Master age group error

### ISSUE THREAD

**Issue by ka121Vantage1610** [djong1/gp3s#184]
Found a bug in the gps-speedsurfing.com website. If you select an event and set the search parameters to super master (61-70) age group it includes speed surfers aged 60 in the search for some reason.
Here’s an example from the Dunkerbeck Speed event: https://www.gps-speedsurfing.com/default.aspx?mnu=eventranking&val=819
Ist place https://www.gps-speedsurfing.com/default.aspx?mnu=user&smnu=equipment&uid=24163 and 3rd place https://www.gps-speedsurfing.com/default.aspx?mnu=user&smnu=equipment&uid=960
Under their profile shows age of 60!

**Comment by djong1** [comment]
Thanks for reporting, we have fixed the bug
