### ISSUE TITLE
Event / One Session/Rider is listed 2 ore more times in Ranking

### ISSUE THREAD

**Issue by blinki-bill** [djong1/gp3s#185]
Hi gp3s Team,
in our event:
https://www.gps-speedsurfing.com/default.aspx?mnu=eventranking&val=769
two riders are listed 2 or 3 times in One Hour Ranking. 
In "Event Edit" the "Rebuild Event Ranking for user" has no success, except that another duplicate session will be added.
Would  you please have a look on it.
Thanks in advance
Werner

**Comment by jhdebruin** [comment]
Forced a full rebuild of the event, all doubles are removed now.
