### ISSUE TITLE
My Sessions > Admin Sessions > Edit Session - wrong fin selected.

### ISSUE THREAD

**Issue by aivoprykk** [djong1/gp3s#19]
Selected is probably first item from the user saved fins list.

**Comment by djong1** [comment]
Thanks for reporting, we will look into this

**Comment by djong1** [comment]
This fix will be delivered in the next release, expected end of next week

**Comment by djong1** [comment]
delivered in production

**Comment by aivoprykk** [comment]
In production still not fixed.
