### ISSUE TITLE
Takoon brand appears twice in Board and none in Sail

### ISSUE THREAD

**Issue by dgpro** [djong1/gp3s#196]
Hi,
Takoon brand now appears twice in Board, none in Sail and once in Fin.
Could you fix it so it appears once in all categories.
Thank you.
![image](https://github.com/djong1/gp3s/assets/12430124/5b4f6c0f-deef-4d69-aa7b-41969cc9adaf)

**Comment by jhdebruin** [comment]
We added Takoon to Sails
