### ISSUE TITLE
Dodgy rankings for United Kingdon and Portland Harbour

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#198]
I've noticed that there are at least two non-existent sessions in the Portland Harbour rankings for 500m.

https://www.gps-foilsurfing.com/default.aspx?mnu=rankings&Year1=-&countryID1=268&Gender1=0&Tab=1&WeightClass1=0&AgeClass1=0&SpeedType1=3

Sessions for Richard Beaman (#2) and Alex Smith (#5) have been deleted but still in the rankings.

**Comment by jhdebruin** [comment]
Hi, @Logiqx i cannot reproduce this, when opening the link an empty page occurs, do you have a screenshot of the page ?

**Comment by Logiqx** [comment]
Ah yes, you need to be logged in.

Here's the screenshot, it's actually UK rankings:

![image](https://github.com/djong1/gp3s/assets/17449078/0c3caa49-f0b7-4dd5-900a-e1dc63377f2e)

**Comment by Logiqx** [comment]
Here's the issue that I meant to report for Portland Harbour:

https://www.gps-foilsurfing.com/default.aspx?mnu=rankings&Year2=-&countryID2=268&SpotID2=681&Gender2=0&Tab=2&WeightClass2=0&AgeClass2=0&SpeedType2=3

![image](https://github.com/djong1/gp3s/assets/17449078/4d0cbf69-c0f4-41b9-88e6-920ec37fab85)

Bob Cartridge is showing 33.10 knots when his session shows 16.65:

![image](https://github.com/djong1/gp3s/assets/17449078/8d1cc31a-ce2d-4d61-9248-ccf97c2375b6)

**Comment by Logiqx** [comment]
The above issues relating to the UK and Portland Harbour both affect multiple speed categories relating to a single run - 10s, 100m, 250m, 500m, etc.

**Comment by jhdebruin** [comment]
@Logiqx  Did some fixes on the rankings , could you please check if ok now ? Indeed could be caused by adjusted sessions

**Comment by Logiqx** [comment]
> @Logiqx Did some fixes on the rankings , could you please check if ok now ? Indeed could be caused by adjusted sessions

The UK rankings have been fixed.

The Portland Harbour rankings still have an issue; e.g. Bob Cartridge 500m of 33.10 knots.

https://www.gps-foilsurfing.com/default.aspx?mnu=rankings&Year2=-&countryID2=268&SpotID2=681&Gender2=0&Tab=2&WeightClass2=0&AgeClass2=0&SpeedType2=3

**Comment by Logiqx** [comment]
@djong1 - As an aside, if the API were to have "Get spot sessions" added, I can potentially re-use the Python code that checks event rankings to check the spot rankings.

At the moment there are 3 API operations - Get event ranking, Get event sessions, Get spot ranking

If "Get spot sessions" is added, I should be able tweak the existing Python code to also check spot rankings with minimal effort.

**Comment by jhdebruin** [comment]
That's strange, pretty sure i corrected the Bob Cartridge listing in the Portland ranking, but it seems to reoccured...  will check it out why this happens....

**Comment by jhdebruin** [comment]
Foil -> https://www.gps-foilsurfing.com/default.aspx?mnu=user&val=388618&uid=24325&spotid=681
Surf -> https://www.gps-speedsurfing.com/default.aspx?mnu=user&val=388620&uid=24325

Both on 25-7-2022 , in RTK Admin both are visible, both sessions seems not be adjusted / corrected

**Comment by Logiqx** [comment]
I've found a speedsurfing session containing the exact speeds in the foilsurfing rankings:

https://www.gps-speedsurfing.com/default.aspx?mnu=user&val=396039&uid=24325

The speeds highlighted in red all appear in the Portland Harbour foilsurfing rankings:

![image](https://github.com/djong1/gp3s/assets/17449078/04586876-bca8-47a0-bf0d-cc70f2ebb039)

**Comment by jhdebruin** [comment]
Must be something like that, just figured out this morning there are two sessions on the sameday , one foil, one surf, so my initial idea was that this somehow mixed up. Will need @djong1 for some more background search on this. Its on the backlog , so it will be sorted out (once :) )
