### ISSUE TITLE
Google Search enhacements

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#199]
members of GPS Speedsurfing, but not active on GPS Wing Foiling. My GPS Speedsurfing profile, including weight and home town, are currently coming up listed in GPS Wing Foiling in a Google Search of me. They should not be publicly available in a Google search. Is there any way to restrict personal details aside from name to GPS Speedsurfing only and to only make them visible to other GPS Speedsurfing members rather than the general public?

**Comment by djong1** [comment]
We have decided to put these kind of information behind the login to fulfil your request.

Changes will be visible from 21 August. Google cache needs to evaporate and it takes time.
