### ISSUE TITLE
My Session > Admin Sessions > Edit Session

### ISSUE THREAD

**Issue by aivoprykk** [djong1/gp3s#20]
Ended event is not in the events list when edit session with attached archived event. As when saved without archived event, not possible to add later on, editing may affect also whole event ranking (guess).

**Comment by djong1** [comment]
Good comment. The rule is that an event session cannot be changed when the event is closed. There is a grace period of 2 day's after the event end date. Event owners want to "freeze" the ranking, so this is why we have this rule implemented. 
If the event owner agrees we can add your session manually.

**Comment by aivoprykk** [comment]
Than would be good to show in session edit view also attached event as "freezed". Otherways as user can edit session, it means that no coherency anymore with historical event data to user session record after you once have saved changes; "freezed" event is just deleted in background.
