### ISSUE TITLE
Add distance to ranking view

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#201]

**Comment by djong1** [comment]
The 24 hour ranking is intended for this, this one filters out the outliers and apply's the rules for real 24 distance. The session distance is unfiltered data above 5 knots.

**Comment by djong1** [comment]
use 24 hour ranking for distance, only apply for autoupload sessions, add distance day ranking ipv map icon

**Comment by djong1** [comment]
implemented
