### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by bert271** [djong1/gp3s#204]
Hi😉

I can't login via facebook.
I have also tried with email login and password

![69D5605C-69E4-48D4-8CE5-551FD9E78CBD](https://github.com/djong1/gp3s/assets/139321254/d1d3c2b0-c4a0-490f-a86d-4c98872d2e6b)

![94881F67-BEB6-4586-BA0B-3AE5A7D0CC3F](https://github.com/djong1/gp3s/assets/139321254/586937ae-891b-4c3b-ac7b-c1efd0c9a8fa)

Mvh Bertil Folke

**Comment by jhdebruin** [comment]
#203 Actual open issue
