### ISSUE TITLE
oh no an Error 500

### ISSUE THREAD

**Issue by nlars2468** [djong1/gp3s#205]
When trying to log in to GPS Speed home site from Google chrome i always get this measage: oh no an Error 500

**Comment by jhdebruin** [comment]
- What OS / Browser versions ? 
- What login type (email Facebook, Google login, etc etc)
- is this only with Chrome ? 
- What happens if you use Icognito mode on Chrome ? 
- Since when does did occur ?

**Comment by nlars2468** [comment]
Hi Jan ! I use Windows 10 home edition as OS. With Google Chrome. When log in to GP3S via Firefox or Edge, then no problem. Via Google chrome i log in with my Google log in account. Log in with icognito mode on chrome, then no log in problem. This problem started late last year  Lars N Skickades från E-post för Windows Från: Jan Hendrik de BruinSkickat: den 17 juli 2023 08:28Till: djong1/gp3sKopia: nlars2468; AuthorÄmne: Re: [djong1/gp3s] oh no an Error 500 (Issue #205) What OS / Browser versions ?What login type (email Facebook, Google login, etc etc)is this only with Chrome ?What happens if you use Icognito mode on Chrome ?Since when does did occur ?—Reply to this email directly, view it on GitHub, or unsubscribeYou are receiving this because you authored the thread.Message ID: ***@***.***> Virusfri.www.avast.com

**Comment by jhdebruin** [comment]
@nlars2468 Please remove cache and cookies for https://gpsspeedsurfingb2c.b2clogin.com/ in Chrome

**Comment by nlars2468** [comment]
I dont know how to do that !

**Comment by jhdebruin** [comment]
@nlars2468 No offence, but please you can google this without any help from us...
