### ISSUE TITLE
Event Sessions will be restricted on 500 issues

### ISSUE THREAD

**Issue by blinki-bill** [djong1/gp3s#206]
Hi GP3S team, 
the shown Event Sessions are restricted on 500 issues:
https://www.gps-speedsurfing.com/default.aspx?mnu=eventsessions&val=769
there are also Sessions with date after 13.07. but they won't be shown. These sessions find place in Event-Ranking but not in Event-Sessions.
Maybe you could change this.
Thanks in Advance.
Werner

**Comment by djong1** [comment]
The error 500 was temporarily and is not affecting the session list anymore. 

The session list is limited to 500 items, this is the cause why you won't see the sessions after 13/07. We have changed this limit to 750. 

I think we have solved the issues and close the topic, feel free to open it again when you have questions. Thanks for reporting and with your help we can make the platform better.
