### ISSUE TITLE
Spot "Belterwijde Kettingbrug" is gone?

### ISSUE THREAD

**Issue by jmans** [djong1/gp3s#209]
What happened to the spot "Belterwijde Kettingbrug", is it renamed to "Belterwijde" ?

"Belterwijde Kettingbrug"  (East of the road) is really another spot then "Belterwijde" (West of the road). 
Different conditions depending on wind direction, an generally much flatter water.

So now i have two times "Belterwijde" in my spot-list, as if someone changed the name of "Belterwijde Kettingbrug".

Is it possible to correct this?

I admit "Belterwijde West" and "Belterwijde Oost" would be better names.

![afbeelding](https://github.com/djong1/gp3s/assets/5877908/f2b8d763-0866-4276-aae7-0b262580c4db)

**Comment by djong1** [comment]
Thanks for submitting this issue. 

Correct, we have merged the spots that are in a Radius of 2,5 km (run locations). We have see in the past years many spots being created that are similar or are just to created to be on the top in a location. 
I can understand that in your case the conditions are different between west and east, but it is every day different so I would say that is why we have the day ranking for a given spot, it shows the ranking in the same conditions for a given spot. 
Does this make sense for you? Can you also discuss this with the local riders?

You can delete one of the double listings for the spots. 

hope this clarity's

**Comment by jmans** [comment]
Thanks for your reply.
I'll ask our locals in the app-group.

**Comment by djong1** [comment]
we close the issue for now, you re-open when it is needed
