### ISSUE TITLE
Keep me Signed In KMSI and improve user login / account reset procedure 

### ISSUE THREAD

**Issue by djong1** [djong1/gp3s#214]
Updated user flow needed to support KMSI

**Comment by jhdebruin** [comment]
@all,

Based on the feedback we received from our customer survey we are deploying a new improved and more simplified login page for all of our platforms. We have also enabled the feature to keep your account logged in for 30 days, so this will reduce the login's during this period big time. Besides this the procedure for resetting password is more user-friendly now. Thnx again for all the feedback we received during the survey, there are lot of improvements to come in the next builds, so stay tuned !

![Screenshot 2023-09-06 at 12 40 18](https://github.com/djong1/gp3s/assets/109060128/e055a2e7-6dcd-43d0-8f17-c2132abfb2a6)


GP3S Crew
