### ISSUE TITLE
Map is not visible to me.  (Chrome on Mac)

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#218]
Map is not visible to me.  (Chrome on Mac) 
<img width="879" alt="image" src="https://github.com/djong1/gp3s/assets/143724473/5572e684-8117-46d1-b76f-788ac41ff0e9">

_Originally posted by @LucSalomons in https://github.com/djong1/gp3s/issues/87#issuecomment-1708142610_

**Comment by kidxrude** [comment]
Ok, can’t see the map on iOS Safari either.

**Comment by jhdebruin** [comment]
- MacOs Ventura 13.5.1 + Safari Version 16.6 (18615.3.12.11.2)
- MacOs Ventura 13.5.1 + Edge Version 116.0.1938.69 (Official build) (arm64)

Both work OK

**Comment by jhdebruin** [comment]
@kidxrude What iphone are you using ??? Here it works like designed -> 

Iphone 14 Pro Max - OS Version 16.6 - Safari 

![IMG_E7229B54CCA7-1](https://github.com/djong1/gp3s/assets/109060128/6113344d-f32d-4d2b-92c5-d71a38d82590)

**Comment by jhdebruin** [comment]
MacOs Ventura 13.5.1 + Chrome Version 116.0.5845.179 (Official Build) (arm64) works fine 
<img width="976" alt="Screenshot 2023-09-06 at 21 58 01" src="https://github.com/djong1/gp3s/assets/109060128/9f957ca7-3b05-4a1a-9032-679a442c2fc9">

**Comment by jhdebruin** [comment]
@kidxrude can you please provide detailed IOS version / phone type etc etc
@LucSalomons can you please detailed MacOS version / Chrome version ?

**Comment by LucSalomons** [comment]
Chrome: Versie 116.0.5845.140 (Officiële build) (x86_64)
Mac OS: Monterey 12.6.6

And yes with Safara the map is visible

**Comment by kidxrude** [comment]
Sorry, this is working correctly now. Same safari / iOS version. Thanks!Sent from my iPhoneOn 6 Sep 2023, at 22:02, Jan Hendrik de Bruin ***@***.***> wrote:﻿
@kidxrude can you please provide detailed IOS version / phone type etc etc
@LucSalomons can you please detailed MacOS version / Chrome version ?

**Comment by jhdebruin** [comment]
@kidxrude thnx we close it for you 😃 

@LucSalomons we checked the log's from yesterday and we had some api errors during the afternoon, looks ok now at the backend, could you give it one more try with Chrome just to be sure ?

**Comment by LucSalomons** [comment]
All good and working now!
