### ISSUE TITLE
adding new sails

### ISSUE THREAD

**Issue by Luca1818** [djong1/gp3s#219]
Adding new sails is not possible at the moment, displays says working.....

**Comment by jhdebruin** [comment]
@Luca1818  Can you provide more info ? What sail type , what page, some screenshots ? Just added some sails here to test, and all works fine it seems

**Comment by Luca1818** [comment]
Hoi Jan Hendrik / Dylan,Ik probeer al een paar dagen een paar Challenger Sails toe te voegen, maar bij het drukken op de button .. adding missing equipment ….. geeft hij alleen working aan. Heb geprobeerd via desktop computer en mobiel. (Zie foto)Met vriendelijke groet, kind regards,Luca ArbouwOp 18 sep. 2023 om 10:46 heeft Jan Hendrik de Bruin ***@***.***> het volgende geschreven:﻿
@Luca1818  Can you provide more info ? What sail type , what page, some screenshots ? Just added some sails here to test, and all works fine it seems

**Comment by jhdebruin** [comment]
Hi Luca, kun je screenshot ook even mailen ? Ik zie hem niet hier namelijk ( info@gps-speedsurfing.com )

**Comment by jhdebruin** [comment]
![Uploading Screenshot 2023-09-18 at 22.04.06.png…]()

**Comment by jhdebruin** [comment]
Issue confirmed: 

- When opening Dashboard, My Items, My Sails, Select Sail Brand [Challenger Sails] , year [2023] , and then selecting 'ADD MISSING EQUIPMENT TO OUR DATABASE'  , the new pope for adding gear doesn't show up, this seems only to occur at the GPS-SPEEDSURFING.COM site ,  at foil it was possible to add the sail ....  @djong1

**Comment by jhdebruin** [comment]
<img width="935" alt="Screenshot 2023-09-18 at 22 04 06" src="https://github.com/djong1/gp3s/assets/109060128/366d5670-8dbd-474b-b64e-354986f94ca6">

**Comment by djong1** [comment]
fix deployed
