### ISSUE TITLE
Missing English text for User Personal Records

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#22]
This is only minor but I thought it worth a mention.

"SESSION_SPEED_Foil" is showing under the user PRs of some users; e.g. Michael George:

https://www.gps-speedsurfing.com/default.aspx?mnu=user&smnu=personalbest&uid=2640

"SESSION_SPEED_Alpha_Racing" is showing under the user PRs of some users; e.g. Antoine Albeau and Hand Kriesel:

https://www.gps-speedsurfing.com/default.aspx?mnu=user&smnu=personalbest&uid=412
https://www.gps-speedsurfing.com/default.aspx?mnu=user&smnu=personalbest&uid=2042

**Comment by djong1** [comment]
thanks for reporting, fixed in next delivery
