### ISSUE TITLE
coros upload  problem

### ISSUE THREAD

**Issue by Erwinrovers** [djong1/gp3s#221]
goodday

today , i wanted to post my session from my coros apex pro, but there was  nothing  to post , in  my dasboard .
i manually downloaded  the session as fit and gpx , but it didn,t show speeds in the post .
on my coros app , i can see al the speeds .

greetings 

erwin rovers

**Comment by jhdebruin** [comment]
We had several Coros sessions uploaded today and yesterday without any issues, so it could be a local glitch. In this case upload in manual , first export it to .FIT from the Coros app, and then use the regular  webuploader ( https://www.gps-speedsurfing.com/mygps.aspx?mnu=mytrackuploadv2 ) . Just in case you could reconfigure the auto-sync ( https://github.com/djong1/gp3s/wiki/How-to-reconfigure-Coros---GP3S-Auto%E2%80%90Sync-Setup)
<image001.png>

**Comment by Erwinrovers** [comment]
Sorry , did upload manually already , same result again , laptop/mobile phone

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Jan Hendrik de Bruin ***@***.***>
Verzonden: Tuesday, September 19, 2023 6:35:50 PM
Aan: djong1/gp3s ***@***.***>
CC: Erwinrovers ***@***.***>; Author ***@***.***>
Onderwerp: Re: [djong1/gp3s] coros upload problem (Issue #221)


We had several Coros sessions uploaded today and yesterday without any issues, so it could be a local glitch. In this case upload in manual , first export it to .FIT from the Coros app, and then use the regular webuploader ( https://www.gps-speedsurfing.com/mygps.aspx?mnu=mytrackuploadv2 ) . Just in case you could reconfigure the auto-sync ( https://github.com/djong1/gp3s/wiki/How-to-reconfigure-Coros---GP3S-Auto%E2%80%90Sync-Setup)
<image001.png>

**Comment by Erwinrovers** [comment]
hi , problem is solved , sorry for the troubles

greetings]

erwin
