### ISSUE TITLE
suunto 9 uploads

### ISSUE THREAD

**Issue by SV1882936** [djong1/gp3s#222]
automatisch sessie's posten met suunto 9 lukt niet.
https://www.gps-speedsurfing.com/?mnu=user&val=422280&uid=27042

https://www.gps-speedsurfing.com/default.aspx?mnu=forum&forum=2&val=203345

https://www.gps-speedsurfing.com/mygps.aspx?mnu=myprofileb2c

![image](https://github.com/djong1/gp3s/assets/145709158/7814633b-3a95-443b-8712-311b71015319)

**Comment by djong1** [comment]
closed

**Comment by SV1882936** [comment]
Goedenmiddag,En is het gelukt om op lossen?Vriendelijke groet,Jerry.Verstuurd met jerry's i-phoneOp 22 jul 2024 om 15:14 heeft Dylan de Jong ***@***.***> het volgende geschreven:﻿
closed
