### ISSUE TITLE
Advanced material search unable to find sessions for 7.8 specifically

### ISSUE THREAD

**Issue by kidxrude** [djong1/gp3s#224]
As a gps-speedsurfing heavy user of the Advanced material search functionality I'd like to find sessions for specific 7.8 sails. 

The problem is when searching for specific sessions that I can only enter a range for a sail size through a dropdown selection which only allows you to select rounded numbers. Would it be possible allowing to enter a sailsize range by using two input boxes where you can enter values manually which also allows a decimal so you can for instance give up the sailrange from 7.5 to 7.8? See also the screenshot as an example.

Maybe this can also come in handy for fin sizes?

Thanks!
![Screenshot 2023-10-02 at 10 39 35](https://github.com/djong1/gp3s/assets/9435/e8bc15da-b4c2-4253-ab31-a27e816b54c1)

**Comment by djong1** [comment]
This can now be achieved with the ChatGPS function, which will replace the current function over time. Please let us now if you can get the desired results with chat GPS: "/my: fastest sessions with a 7.8 sail"
