### ISSUE TITLE
Posting session gives error 500 for specific user (UID = 102 ) 

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#23]
- Logged in with account from user UID = 102
- Uploaded track (multiple tracks tested) 
- After uploading choose specific track from "Updated Session List" with selecting Green + icon
- Error 500 occurs , both on Windows, Mac & IOS

Password & inlog ID available on request from @jhdebruin  

Issue as described reproduced by @jhdebruin

**Comment by djong1** [comment]
The boards equipment dataset was triggering this problem, problem found in board_id 13040 data was malformed, bug fix implemented and problem solved.
