### ISSUE TITLE
Sail material update - edit function malfunctions (rounding)

### ISSUE THREAD

**Issue by LucSalomons** [djong1/gp3s#233]
Hi after adding and updating sails (2024 Duotone Warp_Fin) the sail size gets rounded to 0

Example: sail size 8,4 shows as 8,0 as does 7,8

8,0 should be 8,4
8,0 should be 7,8
7,0 should be 6,8
6,0 should be 5,8
5,0 = 5,0
<img width="878" alt="Schermafbeelding 2023-12-07 om 16 31 48" src="https://github.com/djong1/gp3s/assets/143724473/e605f6f7-2ed3-4fe9-a53c-d07693661c7f">

**Comment by LucSalomons** [comment]
If it is easier for you to just delete these sails, so that I can create new ones; please let me know. But I would like to avoid double entries. The issue that it goed wrong with the rounding after editing a sail will however still remain.

**Comment by jhdebruin** [comment]
> If it is easier for you to just delete these sails, so that I can create new ones; please let me know. But I would like to avoid double entries. The issue that it goed wrong with the rounding after editing a sail will however still remain.

For the short term, please delete them, in the next weeks we have some time to take a closer look and fix it for improvement

**Comment by LucSalomons** [comment]
Thx for the reply. As soon as these are deleted by @djong1 I will create the correct ones. (I Just need to make sure that I don't need to edit them again afterwards, because then the bug arises)

**Comment by LucSalomons** [comment]
I added the correct ones and flagged (the ones where above issues is applicable) the rest for deletion

**Comment by djong1** [comment]
implemented a fix, can you test and let us know?

**Comment by LucSalomons** [comment]
Hi Dylan,

No, not fixed.

1. I added the 2024 Duotone S_Pace 8,8
2. Then I edited this same sail to 7,8
3. Now it shows in the list as: 8,0

KR, Luc

**Comment by djong1** [comment]
oh sorry, was not yet staged to production. Can you please check again...

**Comment by LucSalomons** [comment]
Nope: changed/edited the S_Pace 7,8 to 8,8  and now it shows in the list as 9,0

**Comment by djong1** [comment]
durf het bijna niet te vragen, maar kan je nog een testje doen?

**Comment by djong1** [comment]
nice, we kunnen ook materiaal lijsten in bulk importeren, maar de leveranciers zijn vaak te lui om die aan te leveren. Maar als je die hebt voor DUOTone dan kan dat ook gebruikt worden.
