### ISSUE TITLE
Upload 10 Hz gpy / sbp files fails some times, filter issue ?

### ISSUE THREAD

**Issue by RP6conrad** [djong1/gp3s#237]
When uploading a 10 Hz gpy / sbp file from a ESP-GPS logger, sometimes the upload fails. Reading the files with GSP-results and GPS-speedreader however is possible. After converting the file to a 5 Hz (delete every second frame), the upload is possible.
Message window from gps-speedreader : 
**File: M10_BE182__2312281010.gpy
No problems reading M10_BE182__2312281010.gpy

Observed time distribution (in ms): 
99 1
100 108353
101 1

Points with untypical dt (and speed > 5.0 knots):
1  101 ms at #45460 11:27:12.401 speed: 13.243 sAcc: 0.157
2  99 ms at #45467 11:27:13.100 speed: 10.067 sAcc: 0.259
2 time errors (2 above 5.0 knots), about 0 missing points
1489 filtered points:
  Satellites 1390 points; max speed: 9.0 kn 
  SDOP/sAcc 1458 points; max speed: 10.6 kn 
  Acceleration 14 points; max speed: 19.9 kn 

Filters were applied
Start: 28/12/2023 08:11:26.400 end: 28/12/2023 11:12:01.900
Assumed wind direction: 206 degrees

Files and colors:
M10_BE182__2312281010.gpy - blue**

**Comment by jhdebruin** [comment]
@RP6conrad  could you share some examples here ?
