### ISSUE TITLE
Display full track doesn't show track - Premium Feature

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#238]
When selecting "View Track on Map"  - only empty map displays

Issue occurs with

- Chrome, Windows 10/11
- Edge, Windows 10
- Firefox, Windows 10
- Chrome, MacOS 14.1.1
- Edge, MacOS 14.1.1
-

All displays correct when using

- Safari 17.1 , MacOS 14.1.1

**Comment by jhdebruin** [comment]
<img width="685" alt="image003" src="https://github.com/djong1/gp3s/assets/109060128/9cb44a21-3427-48f3-b358-7f9e7a40eccc">

**Comment by djong1** [comment]
please provide link to session

**Comment by gerritsan** [comment]
https://www.gps-speedsurfing.com/default.aspx?mnu=sessionmap&sessionid=429750&val=7693ac2ff0a846fd805dc29003c23878&track=no

have same problem,with google chrome,microsoft edge....think my last 4/5 sessions have this problem.
also looking at other tracks of other riders.
cleaned up browser history,cookies....ect

**Comment by djong1** [comment]
Houtrib is ok, makkum does not scroll on year baseline, lauwersoog does not show

**Comment by jhdebruin** [comment]
We found some issues, we expect a new build to be deployed at 17:00 CET today (5-1-2024) , could you please do some test and share the results after that timeslot @gerritsan ?

**Comment by gerritsan** [comment]
Hello ,
I will test some sessions again after 17.00.
Will let you know how it went.
Greets gerrit

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gerritsan** [comment]
https://www.gps-speedsurfing.com/default.aspx?mnu=user&val=429587&uid=5967

This session post with the motion.
If i select show track or show runs  both options show the track and runs on the map, only the 500m animation does not work,only map,no run of 500m on it.
Greets gerrit

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jhdebruin** [comment]
Thnx for the feedback,  good to see the first two issues are solved, @djong1 expect the same root cause as the previous one s i assume
