### ISSUE TITLE
Posting track doesn’t show track info

### ISSUE THREAD

**Issue by WingMic** [djong1/gp3s#241]
When a track is uploaded and you post the track (click on the + button), you choose spot+board+fin+sail and enter remarks) there normally allways was info underneath with your tracks speed data. This is missing/not present anymore. I have asked others they also do not see this info anymore. Only after posting you can see the data. Any reason for this / is this a bug? Checking the data before posting normally shows if the data is correct before you press the add/toevoegen button..?

**Comment by gerritsan** [comment]
i think have the same problem.
when posting a session and want to see my track or runs on map,the map is vissible but the line of the runs or not.
tryed to delete webhistory,cookies...ect.
tried on smartphone samsung s10 and on my notebook lenevo

**Comment by jhdebruin** [comment]
Hi, this is a part of the redesign, so no bug.  The data displayed before posting is/was static and can not be edited anyhow.

**Comment by WingMic** [comment]
That’s to bad, i used it a lot to compare gps data from multiple devices before posting as did many others. Also preventing posting strange numbers.

**Comment by jhdebruin** [comment]
Thnx @WingMic for the feedback, the intention was to make it easier, we will plan a rollback in next weeks, so it will show up again

**Comment by djong1** [comment]
not considering anymore
