### ISSUE TITLE
[BUG] Gyro 1 duplicated on website

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#242]
### Describe the bug

The following page lists Gyro 1 twice:

https://www.gps-speedsurfing.com/default.aspx?mnu=item&item=GPSInfo

### Expected behavior

Gyro 1 should be listed once

### Actual behavior

Gyro 1 is listed twice

### Reproduction Steps

Open web page :)

**Comment by djong1** [comment]
updated thanks for reporting
