### ISSUE TITLE
[BUG] GW-52 is named incorrectly - GX-52

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#243]
### Describe the bug

Website names GW-52 incorrectly on the following pages:

https://www.gps-speedsurfing.com/default.aspx?mnu=item&item=GPSInfo
https://www.gps-speedsurfing.com/default.aspx?mnu=item&item=GX52

### Expected behavior

The device should be called GW-52

### Actual behavior

The device is called GX-52

### Reproduction Steps

Open the web pages :)

**Comment by djong1** [comment]
updated and solved, thanks for reporting

**Comment by Logiqx** [comment]
@djong1 - Second page seems to be fixed, but first page still saying GX-52

https://www.gps-speedsurfing.com/default.aspx?mnu=item&item=GPSInfo

**Comment by jhdebruin** [comment]
Adjusted the text on that page also
