### ISSUE TITLE
[FEATURE] Add GPS type to API data

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#244]
### Website

All website APIs

### Please describe the feature.

Perhaps you can include the GPS type between “sessionfin” and “sessionsail” in the JSON files?

That would allow me to generate some stats for the devices being used nowadays.

**Comment by djong1** [comment]
added now to the api's

**Comment by Logiqx** [comment]
@djong1 Thanks.

A quick look at the data has been quite insighful, but I'll look to produce some nice stats when I have a bit of time.
