### ISSUE TITLE
[BUG] Duplicates in the event rankings

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#245]
### Describe the bug

There are suplicates in the event rankings.

See https://logiqx.github.io/gp3s-query/ for details

### Expected behavior

No duplicates should be present

### Actual behavior

Duplicates are present

### Reproduction Steps

Have a look at the events on https://logiqx.github.io/gp3s-query/ and click through to rankings affected

**Comment by djong1** [comment]
@jhdebruin can you manualy update the rankings for these affected users?

**Comment by jhdebruin** [comment]
Updated by admin module
