### ISSUE TITLE
[BUG]Waterspeed integration

### ISSUE THREAD

**Issue by richieb362** [djong1/gp3s#246]
### Describe the bug

Tracks sent from Waterspeed app are hanging on upload and are unable to be posted

### Expected behavior

Track should upload automatically ready to be posted

### Actual behavior

Upload hangs

### Reproduction Steps

Post a file from Waterspeed

**Comment by Logiqx** [comment]
Here is a screenshot that Richard sent me for this particular issue:

![image](https://github.com/djong1/gp3s/assets/17449078/2b4925ac-0d14-401d-85f4-cd5bc6be6935)

**Comment by jhdebruin** [comment]
Can you please provide the export tracks in gpx format, also please device type and ios version (or watchos)

**Comment by djong1** [comment]
I can see the posted sessions on gps-wing, are these the ones you are missing? Or are the uploaded files not visible at all?

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Jan Hendrik de Bruin ***@***.***>
Verzonden: Wednesday, February 28, 2024 9:57:16 PM
Aan: djong1/gp3s ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: Re: [djong1/gp3s] [BUG]Waterspeed integration (Issue #246)


Can you please provide the export tracks in gpx format, also please device type and ios version (or watchos)

**Comment by richieb362** [comment]
Yes, the tracks have uploaded to gps wing. The files are still hanging on the Post Track page

**Comment by djong1** [comment]
All activities are completed and we show this page to show the status only.

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: richieb362 ***@***.***>
Verzonden: Wednesday, February 28, 2024 10:25:10 PM
Aan: djong1/gp3s ***@***.***>
CC: Dylan de Jong ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [djong1/gp3s] [BUG]Waterspeed integration (Issue #246)


Yes, the tracks have uploaded to gps wing. The files are still hanging on the Post Track page
