### ISSUE TITLE
Merge Spots Neusiedlersee and Neusiedler Sea (Austria)

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#247]
### Describe the bug

Regarding Spots, there is Neusiedlersee and Neusiedler See – being the same lake, just spelled differently. Is there a chance to combine them under one name?

### Expected behavior

Regarding Spots, there is Neusiedlersee and Neusiedler See – being the same lake, just spelled differently. Is there a chance to combine them under one name?

### Actual behavior

Regarding Spots, there is Neusiedlersee and Neusiedler See – being the same lake, just spelled differently. Is there a chance to combine them under one name?

### Reproduction Steps

Regarding Spots, there is Neusiedlersee and Neusiedler See – being the same lake, just spelled differently. Is there a chance to combine them under one name?

### Environment

Regarding Spots, there is Neusiedlersee and Neusiedler See – being the same lake, just spelled differently. Is there a chance to combine them under one name?

**Comment by djong1** [comment]
combined, thanks for reporting
