### ISSUE TITLE
[BUG] profile picture not updated

### ISSUE THREAD

**Issue by djong1** [djong1/gp3s#249]
### Describe the bug

something with CDN path update?

### Expected behavior

-

### Actual behavior

-

### Reproduction Steps

--

### Environment

--

**Comment by gerritsan** [comment]
Tryed also to update profile picture.
Upload file/foto (jpg) see new picture. 
But don't see a button where you can save it(bijwerken)  by other elements in menu profile there buttons to save it.

**Comment by djong1** [comment]
Make sure you selected a fil, PNG or JPG and click Upload File

![image](https://github.com/user-attachments/assets/ec452fbf-6889-4754-91f8-938b1f05f3f7)
