### ISSUE TITLE
My Sessions > Admin Sessions > Edit session > Event

### ISSUE THREAD

**Issue by aivoprykk** [djong1/gp3s#25]
In session edit view attached event missing after save when event is archieved. Should be carried through persisting process.

__Originally posted by @aivoprykk in https://github.com/djong1/gp3s/issues/20#issuecomment-1207004793__

**Comment by Logiqx** [comment]
It is worth noting that work in progress by the GP3S team will ultimately provide support for multiple events per session.

Users won't need to manually select the event(s) when posting or updating sessions. Selection of events (and persistence when editing sessions) will be an automatic / invisible process.

Comment by @djong1 - https://github.com/djong1/gp3s/issues/18#issuecomment-1207293031

> To give you a bit more insight: we are currently in the transition from 1 to 1 relations between session and event to 1 to many. To give users the opportunity to attach the session to multiple events. We do this first for the events rankings and for events that run on global or country level. We do that in coexistence to slowly transition (in a controlled manner) towards this new model. In the end: the event name will be removed from the session detail page, once a user is subscribed to an event his session will be automatically added to the event, the event selection will be removed from the add session page when posting.

**Comment by djong1** [comment]
As @Logiqx mentioned above this issue will be resolved by the new feature we plan to complete by end of this month.

**Comment by aivoprykk** [comment]
Thanks for multi events development! New approach is generally good too. But as user i would be happy to choose/drop event also after session is saved. For example use case i have saved session, but join with event after. For new approach i have to drop session and upload it again after add event to my events list. So current approach from user point is also good and we add event to session later quite often. Dropping event from session is rarely used but i have case myself this year. As i have in list local event where countable sessions should be done only on local spots, i had to delete event which results where done not in local spot. With new approach probably there should be solution for that as well.

**Comment by Logiqx** [comment]
@aivoprykk 

All of these scenarios / requirements can be automated but it is good for you to have given your specific examples.

The GP3S team can capture these requirements and build support into the new automated solution.

**Comment by djong1** [comment]
@aivoprykk, that is indeed what we have automated now when afterwards sign-up it will add also historic sessions and rankings, so no need any more for the user to figure this out manually.
