### ISSUE TITLE
[BUG]mark hayford - Super Master Ranking not updated

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#250]
### Describe the bug

Op 28 mrt 2024 om 13:43 heeft mark hayford <[markhayford@hotmail.com](mailto:markhayford@hotmail.com)> het volgende geschreven:

﻿
Hi Jan

Here's links to two different sessions. Both sessions are after I turned 61.

https://www.gps-speedsurfing.com/default.aspx?mnu=user&val=428805&uid=960

https://www.gps-speedsurfing.com/default.aspx?mnu=user&val=433895&uid=960

Many thanks
Mark

 
From: Jan hendrik de Bruin <[jbr@gps-speedsurfing.com](mailto:jbr@gps-speedsurfing.com)>
Sent: 28 March 2024 12:20
To: mark hayford <[markhayford@hotmail.com](mailto:markhayford@hotmail.com)>
Subject: Re: Super master ranking
 
Hi Mark,

Can you give me a link to your profile or latest session ? 

Mvgr.

Jan Hendrik de Bruin

Op 28 mrt 2024 om 12:57 heeft mark hayford <[markhayford@hotmail.com](mailto:markhayford@hotmail.com)> het volgende geschreven:

﻿
Hi Jan, I hope you are well.

Can you help please?

Since I turned 61 last December (61-70 super masters age group), non of my sessions are showing in super master ranking. My birth date is correct in my membership data.

Hopefully it is a simple fix?

Many thanks & best regards
Mark Hayford

From: Jan hendrik de Bruin <[jbr@gps-speedsurfing.com](mailto:jbr@gps-speedsurfing.com)>
Sent: 28 March 2024 12:20
To: mark hayford <[markhayford@hotmail.com](mailto:markhayford@hotmail.com)>
Subject: Re: Super master ranking
 
Hi Mark,

Can you give me a link to your profile or latest session ? 

Mvgr.

Jan Hendrik de Bruin

Op 28 mrt 2024 om 12:57 heeft mark hayford <[markhayford@hotmail.com](mailto:markhayford@hotmail.com)> het volgende geschreven:

﻿
Hi Jan, I hope you are well.

Can you help please?

Since I turned 61 last December (61-70 super masters age group), non of my sessions are showing in super master ranking. My birth date is correct in my membership data.

Hopefully it is a simple fix?

Many thanks & best regards
Mark Hayford

### Expected behavior

Should be listed

### Actual behavior

Not listed

### Reproduction Steps

See links

**Comment by djong1** [comment]
![image](https://github.com/user-attachments/assets/6c46089d-b2a5-4ad6-b8a3-dfb505c47837)


Issue is solved. Be aware that a personal record is recorded under the age group when you achieved the record. We do not have PB per age group.
