### ISSUE TITLE
GPX Upload file from Garmin Forerunner 45

### ISSUE THREAD

**Issue by KaaimanWSB** [djong1/gp3s#251]
### Website

windsurf

### Query/Question

Dear Support,
My TomTom Sports is not supported anymore.
Therefore i bought Garmin Forerunner 45
I am testing if the GPX file is ok. 
Unfortunately it is not
These are the details:    23-4-2024: 07:25 | id: 403957

Question: do  you know what i must adjust in the logging, to make the file working?

NB: i tested the same with a Garmin Forerunner 245 These are the details:    23-4-2024: 07:15 | id 403956
       this was ok.
       
       Regards Kaaiman

**Comment by jhdebruin** [comment]
https://github.com/djong1/gp3s/wiki/How-to-configure-your-Garmin-Device

**Comment by KaaimanWSB** [comment]
Hi Jan Hendrik, thank you for quick feedback!
I will go ahead with the advice in the link.
My first observation is that i cannot set "Every Second Recording" .
Maybe a software update on my watch will help..........
For know my question is answered.
Case can be closed
