### ISSUE TITLE
[BUG] there is no national flags for both South Korea 🇰🇷 and Vietnam 🇻🇳

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#252]
### Describe the bug

 there is no national flags for both South Korea 🇰🇷 and Vietnam 🇻🇳

### Expected behavior

 there is no national flags for both South Korea 🇰🇷 and Vietnam 🇻🇳

### Actual behavior

 there is no national flags for both South Korea 🇰🇷 and Vietnam 🇻🇳

### Reproduction Steps

see screenshot
![IMG_5545](https://github.com/djong1/gp3s/assets/109060128/a07420e7-9dd2-49ff-bfad-42849b7666d3)

**Comment by D990905** [comment]
How to solve it?

**Comment by jhdebruin** [comment]
Will be on the backlog, so can be fixed @D990905
