### ISSUE TITLE
I can't log

### ISSUE THREAD

**Issue by Philouwind** [djong1/gp3s#255]
### Describe the bug

Hello, I can't log in to my account. I haven't logged in for several years and I don't want to lose all my data. How can I do ? The procedure with the verification code does not work for me. THANKS. Philippe Lesselin

### Expected behavior

Be able to log in

### Actual behavior

Impossible to log

### Reproduction Steps

The lost password procedure does not work for me.

### Environment

mac sonoma

**Comment by jhdebruin** [comment]
Fixed, please check mail
