### ISSUE TITLE
2024 The Summer Edition- Dunkerbeck Speed Challenge

### ISSUE THREAD

**Issue by Boris999120** [djong1/gp3s#257]
### Describe the bug

Hi there !
I was registered since the 01 sept and ranking into the evenement "2024 The Summer Edition- Dunkerbeck Speed Challenge", and few day ago i suddenly disappered from the listing and ranking.
And in my evenement list nothing !
My name is Boris FAGNART.
Thanks
Have a nice day !
Boris.

### Expected behavior

SO

### Actual behavior

SO

### Reproduction Steps

So

### Environment

So

**Comment by jhdebruin** [comment]
Hi @Boris999120 , do you have a link to your fastest session in the event ?

**Comment by jhdebruin** [comment]
Received no feedback, issue closed
