### ISSUE TITLE
[BUG] settings menu missing after update

### ISSUE THREAD

**Issue by raymond-w** [djong1/gp3s#258]
### Describe the bug

When opening the website the settings menu option is missing.
Website is standard on KTS and via that specific menu I changed it to KMH.
After discussing I'm not the only one missing this feature.

### Expected behavior

Show a menu option to change settings.

### Actual behavior

No settings menu visible.

### Reproduction Steps

Tried 

### Environment

Tried other browsers and discussed it with peers.
- Linux / Firefox 
- macOS 
- IOS
- Windows10 / Firefox
- Android / Firefox

**Comment by jhdebruin** [comment]
@raymond-w Some fixes are deployed, could you please confirm its fixed ?

**Comment by raymond-w** [comment]
Yes, this fixes it on Android and IOS.
Need to check laptop when I have access.
Tx!
