### ISSUE TITLE
"Ghost"  500-meters still appears in GPS-Foilranking Personal Best  - One individual rider (UID 24525) 

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#27]
gps-foilsurfing (Ben):

PRs still contain ghost scores (e.g. 500m)

https://www.gps-foilsurfing.com/default.aspx?mnu=user&smnu=personalbest&uid=24525

Have done several Rebuilds, but issue still remains

**Comment by Logiqx** [comment]
@djong1 you can close this one now as you fixed the bug.

**Comment by djong1** [comment]
solved
