### ISSUE TITLE
Enhance Start and End Dates of Events 

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#28]
Would be nice to follow a more logical format for start and end dates of events,   so when an event starts at 1-1-2023 and end at 31-12-2023 this also should be the dates we enter in the Event Admin Module

When the year(s) of the event are know (and we do after we have entered start and end date) the name for the event could be auto generated like 

YYYY (-YYYY) The Name of the Event ,  

An other option could be a Year filter / View in the Running Events page

**Comment by djong1** [comment]
implemented

**Comment by Logiqx** [comment]
@djong1 Probably worth tweaking the default end date to 31/12

![image](https://user-images.githubusercontent.com/17449078/183603279-128ada4f-db9a-437b-a0f2-27c40af3ada3.png)

**Comment by jhdebruin** [comment]
@djong1 Very nice, the new module works fine, world, country and spot ok ! And auto add of year before the event name, this will give a bit more standard look and feel !
