### ISSUE TITLE
Login with Microsoft account gives error "Invalid request"

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#38]
Login with Microsoft Account gives the following error message

"invalid request: The provided value for the input parameter 'redirect ur' is
not valid. The expected value is a URI which matches a redirect URI
registered for this client application.
![image0](https://user-images.githubusercontent.com/109060128/183762225-478c34bd-c764-40d3-9445-8aba11b197f3.png)
"

**Comment by jhdebruin** [comment]
Reported by multiple users today

**Comment by djong1** [comment]
In preparation of the change on the 27 of August the return url is changed. Applied a fix, can you verify with the users

**Comment by jhdebruin** [comment]
Confirmed and fixed !
