### ISSUE TITLE
Rogue reading in PRs and rankings

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#42]
I can see a rogue reading on gps-foilsurfing in the 500m rankings. Ben Clothier 28.71 knots:

![image](https://user-images.githubusercontent.com/17449078/185911884-b383549b-3b25-44f2-b6de-694a0f16f666.png)

![image](https://user-images.githubusercontent.com/17449078/185911973-8deb3ea4-d791-4aae-b7e4-80305af58544.png)

It is also present in the world rankings.

This appears to have been from a fin session that was subsequently deleted.

**Comment by Logiqx** [comment]
I have realised this is a duplicate of #27

**Comment by djong1** [comment]
Thanks for reporting! Bug identified, ranking updated
