### ISSUE TITLE
Incorrect Rankings for Twann in 2022 Funsport Makkum GPS Speed Challenge

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#46]
This appears to be the only event with incorrect rankings. Perhaps related to the event being for a single spot?

![image](https://user-images.githubusercontent.com/17449078/188304263-dba9bbbb-342c-4430-8a1a-93eeec71fe30.png)

**Comment by jhdebruin** [comment]
Rebuild and checked
