### ISSUE TITLE
Home Banners update for wingfoiling

### ISSUE THREAD

**Issue by djong1** [djong1/gp3s#47]
@jhdebruin update homebanners for foil and wingfoil

**Comment by Logiqx** [comment]
Do you have an eta for gps-wingfoiling.com?

**Comment by jhdebruin** [comment]
Yes.... this week.... its already active, but domain name has to be linked [https://www.gps-waszp.com]

**Comment by jhdebruin** [comment]
@Logiqx  its up and running now... -> https://www.gps-wingfoiling.com
