### ISSUE TITLE
Login Gps-Wingfoiling does not work

### ISSUE THREAD

**Issue by WingMic** [djong1/gp3s#50]
Login page doesn’t show and after pressing the login button it becomes an enless loop. On iphone 11.
![50B8F696-6341-4AEB-9C10-402EBEED2B94](https://user-images.githubusercontent.com/114137516/191681404-cca08981-467e-4bb7-bf5d-2b77e9795073.png)

**Comment by djong1** [comment]
thanks for reporting, solved now
