### ISSUE TITLE
Wingfoiling - Adding Boards

### ISSUE THREAD

**Issue by unclechunk** [djong1/gp3s#53]
When adding my kit, the only "board class" options are for windsurfing related, could do with a "Wing foil" type.

**Comment by djong1** [comment]
Fix created and deployed to production, release 35698. please confirm @unclechunk

**Comment by unclechunk** [comment]
Looks good, I’ve used “foilboard” for my Wingfoil Board.

**Comment by djong1** [comment]
CLOSED
