### ISSUE TITLE
Wingfoiling - Foils

### ISSUE THREAD

**Issue by unclechunk** [djong1/gp3s#54]
I can't add my foils as you don't give us an option to Add, even though it says "only add if it's not in the list".
This may need a few more options than the windsurfing page as you'll need mast, front foil, rear foil, fuselage.

**Comment by djong1** [comment]
So your ask is to have more parameters in the list, the needed parameters are: 

1. Brand
2. Name
3. production year (numeric)
4. Mast size (numeric)
5. Front Foil (description or numeric?)
6. Rear Foil (description or numeric?)
7. Fuselage (description ?)

please advise if this list is correct

**Comment by unclechunk** [comment]
Yes, that looks correct

**Comment by djong1** [comment]
@unclechunk should 5, 6 and 7 be numeric or tekst?

**Comment by unclechunk** [comment]
Probably text (5, 6 and 7) as some are measured in volume and others in size and others in text (e.g. xxl or TC70, etc.).

**Comment by djong1** [comment]
Fix created and deployed to production, release 35698. please confirm @unclechunk

**Comment by unclechunk** [comment]
It shows as “Add a new fin", can it say "Add a new Foil".

Example data (this is my foil):

Foil Brand: Simmer
Front Wing Size: 1600
Rear Wing Size: 310
Fuselage length: 650mm
Mast length: 750mm (placeholder says “fin length”)
Category: Aluminium / Carbon
Prod. Year: 2022

**Comment by djong1** [comment]
New build deployed with additional fix please test

**Comment by djong1** [comment]
skipped category (too many parameters otherwise)

**Comment by unclechunk** [comment]
This isn’t complete as far as I can tell?
The brand isn’t saving from the add new fin form, its still taking the brand from the form before.
Only the second form has Simmer in it, the first list of brands is still different to the second and “Simmer” isn’t there or Cabrinha and maybe a few other Foil brands.

**Comment by unclechunk** [comment]
Also the table at the top doesn't list the front wing and rear wing and fuselage sizes.
We don't really need category as that can be in the "type" box or the logo column.
PS. I've added a couple of entries trying to get it into the system, can you remove the "Blackbird 75 Foil" one. Obviously myself and someone else have had to bypass the brand field and put it into the "Type" field description because the brand isn't available.

**Comment by unclechunk** [comment]
Nearly there.
It wouldn’t let me save the Brand “Simmer”

If I select any brand (as Simmer isn’t there) then click Go.

This then gives me the “Add missing equipment our database”
When I click this it then gives me a slightly different brand list that does include “Simmer”, when I select/add all the details for the new item, it doesn’t save everything in that form, it saves the random brand I selected to get the form to display.
Also the table with the list of fins, doesn’t show all the fields in the form.
