### ISSUE TITLE
Wingfoiling - Sails

### ISSUE THREAD

**Issue by unclechunk** [djong1/gp3s#55]
I can't find any sails to select for my quiver and when I add a new one (even though its listed in my sails), this also isn't found.
So the search and listing of the sails are not displaying, so we might be adding duplicates.
Maybe should be called "Wings" and not "Sails" as well?

**Comment by djong1** [comment]
Thanks. The Idea implemented, is to have a separate Quiver list for wingfoiling, since the foils differ from the sails. the effect is that you need to add the wings to the database (create new) and that is why you do not see any wings in the list. So please add your wings. Based on your comment I think it is best to filter also the personal quiver list, because this is now showing all quiver. agree?

**Comment by unclechunk** [comment]
I have already added 1 wing to my quiver under GPSwingfoiling but if I then do a search it still doesn’t bring any sails up, not even the one I’ve added.
It also says “Add new equipment to the gps-speedsurfing database”, is this why its not searchable in gps-wingfoiling ?

Your brand list doesn’t have “Slingshot” in the list or a few other wing brands and there’s nowhere to add them?
Slingshot, Gong, f-One, Ozone, Cabrinha, Ensis, Hyde, I’m sure there are a lot more.

This means I can’t add my other wings.

Many thanks
Anthony

**Comment by jhdebruin** [comment]
Hi, i will add some of the brands listed above, so you can proceed adding gear

**Comment by unclechunk** [comment]
Thanks, I’ve added 3 sails to my quiver, however the “search text” area still doesn’t bring any options up, if I type “slingshot”, I’d expect it to bring at least my 2 options up, is that not how it should work?
Regards
Anthony

**Comment by jhdebruin** [comment]
@unclechunk yes, it should, not sure it takes some time to index it, will take a look tomorrow, just to check this out

**Comment by djong1** [comment]
Fix created and deployed to production, release 35698. please confirm @unclechunk

**Comment by unclechunk** [comment]
I have added my wings and the search is bringing something up but none of my “Wings” are in the list, the returned list only shows windsurf sails?

**Comment by djong1** [comment]
New build deployed with additional fix please test

**Comment by unclechunk** [comment]
Thats a fix.
Thanks
