### ISSUE TITLE
Wingfoiling - Garmin Sync

### ISSUE THREAD

**Issue by unclechunk** [djong1/gp3s#56]
I have setup my Garmin account with your API but none on the activities have come across, any idea why (it says "No activities") and yes the activities are marked as "Windsurfing" in Garmin?

**Comment by djong1** [comment]
did you setup the Garmin on the wingfoil website or on another site?

**Comment by unclechunk** [comment]
Thats a good point, I’m not sure, I know it returned me tog psd-speedsurfing after it had completed.
Is there any way to change that as it shows its connected in my account?
Thanks
Anthony

**Comment by unclechunk** [comment]
Hi,
So the process currently works like this. From the wing foiling site you click on the “works with the app Garmin.connect” button.



When you click on that it takes you to gps-speedsurfing.com:



Then you click “ok" and it links you up and then sends you back to gps-speedsurfing.com and NOT gps-wingfoiling. Although it does show that my account is linked in gps-wingfoiling.com:




But under “My Sessions” it shows “No data found”...




From my Garmin Connect…



I would have hoped it would have brought a few off these across?
Thanks
Anthony

**Comment by djong1** [comment]
After connecting, Garmin will only sync new added workouts of type windsurfing. So you must do a workout first after connecting. Did you do a workout?

**Comment by unclechunk** [comment]
On that note, all of my windsurfing activities are set after the activity has been uploaded as my watch doesn't give me the option to set the activity to "windsurfing" at source.
So I assume that my "workout" as it's initially uploaded, gets ignored and then when I change the activity to "windsurfing" your system never sees it because it's in the past.
Does that sound correct?

Can you not just sync with the API from the date that year that I signed up or have a re-sync button that would re-check within a week or something?

**Comment by unclechunk** [comment]
Yes I do, but this also only records the activity as a “workout” not as “Windsurfing"

**Comment by djong1** [comment]
can you share a link to a posted session that you posted?

**Comment by unclechunk** [comment]
I've manually tried to add this one (yesterday) to your system as a fit file:
https://connect.garmin.com/modern/activity/9679644227

Here's a test one I did today to see if it would sync:
https://connect.garmin.com/modern/activity/9689810054

The page is now showing 3 uploaded sessions but none of these seem to have any data:
![Screenshot 2022-09-28 at 10 11 24](https://user-images.githubusercontent.com/2725484/192739530-beb9f50c-1e13-46b8-b09e-a4b5b1daa639.png)

**Comment by unclechunk** [comment]
I've recently pressed the + and added these sessions by filling in the extra data.
Unfortunately the 3 I've added I can no longer see anywhere. I do however have some data to the right on that page.
So there obviously is some data and some sessions?

![Screenshot 2022-10-01 at 18 19 37](https://user-images.githubusercontent.com/2725484/193420850-eeb05973-5d14-48db-836f-80dc65a3e16e.png)

**Comment by jhdebruin** [comment]
What name have you posted ?

**Comment by unclechunk** [comment]
Sorry, I’m not sure what you mean?

**Comment by jhdebruin** [comment]
Under What user/display name are you posting ?

**Comment by unclechunk** [comment]
Anthony York

**Comment by unclechunk** [comment]
Manual uploading seems to be working ok now. I'm not sure if its because I'm now uploading gpx files instead of fit?
Anyway I've manually added a few.
I'll keep an eye on the Garmin sync to see if my latest sessions upload.

**Comment by jhdebruin** [comment]
For Garmin its best to use .GPX , in the .FIT extension there are multiple hickups we cannot process, for Coros devices is best to use .FIT because it has the advanced filters in it...
