### ISSUE TITLE
Wingfoiling - Garmin Linking

### ISSUE THREAD

**Issue by unclechunk** [djong1/gp3s#57]
Maybe just a simple fix this one.
When you link up to Garmin, it then returns you to gps-speedsurfing.com not gps-wingfoiling.com

**Comment by djong1** [comment]
Unfortunately, this is for now a given we won't fix soon. Garmin API will be changed soon and hopefully they will support multiple redirects. 
Keep it on the backlog for monitoring Garmin updates

**Comment by jhdebruin** [comment]
Tested and its working ok now
