### ISSUE TITLE
Prepare API's for Waterspeeds

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#59]

**Comment by jhdebruin** [comment]
API documentation send

**Comment by djong1** [comment]
asked for problem description since the team reported that they have problems connecting

**Comment by MaxMaxP** [comment]
if you try to upload a gpx exported with WS through the website (not the API) is it not working
[Waterspeed-2023-02-12-14.15.27.gpx.zip](https://github.com/djong1/gp3s/files/10950188/Waterspeed-2023-02-12-14.15.27.gpx.zip)
