### ISSUE TITLE
Auckland Windsurfing Association Speed Challenge 2021 appears to have no historical data

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#60]
Auckland Windsurfing Association Speed Challenge 2021 appears to have no session and ranking data

https://www.gps-speedsurfing.com/default.aspx?mnu=event&val=690

**Comment by jhdebruin** [comment]
https://www.gps-speedsurfing.com/default.aspx?mnu=user&val=372611&uid=4364

https://www.gps-speedsurfing.com/default.aspx?mnu=user&val=372629&uid=4364

https://www.gps-speedsurfing.com/default.aspx?mnu=user&val=372749&uid=4364

https://www.gps-speedsurfing.com/default.aspx?mnu=user&val=368687&uid=4364

**Comment by djong1** [comment]
solved, we need to set event scope first for historic events before rebuilding
