### ISSUE TITLE
Auto upload of OAO file not appearing 

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#61]
I'm trying to upload a session from my Motion but it never appears in the uploaded sessions list.

The screenshot below shows two sessions uploaded by my COROS today but not the Motion one I've tried to upload from home.

![image](https://user-images.githubusercontent.com/17449078/192360245-bb9a460f-ce30-4bc2-b0d6-f4f628afa023.png)

**Comment by djong1** [comment]
I think it has been auto remediated, triggered by a container health message. @Logiqx please confirm it is working again. 

NEED TO FIX: lower the container health time span

**Comment by Logiqx** [comment]
@djong1 - It still doesn't seem to be appearing for me.

![image](https://user-images.githubusercontent.com/17449078/192467463-d10027d4-bbe3-4736-9fb9-d64eff2a3831.png)

**Comment by Logiqx** [comment]
@djong1 - I also seem unable to upload using GPSResults. Username set to my e-mail, password corrrect.

**Comment by Logiqx** [comment]
@djong1 - I can provide the file and / or my login details via PM if you would like to test.

**Comment by djong1** [comment]
yes please

**Comment by djong1** [comment]
Fix created and deployed to production, release 35699. please confirm @Logiqx

**Comment by Logiqx** [comment]
I'm still unable to use the auto-upload but now figured out that GPSResults requires a different password.

So, I can upload via GPSResults but not using the web upload.

**Comment by Logiqx** [comment]
Further info:

Simon Chippington has reported problems uploading to gps-wingfoiling as well.

He says that he can upload to gps-foilsurfing and then the track is visible in gps-wingfoiling as well.

**Comment by djong1** [comment]
we tested today and we can upload our stuff, can you have a try with and report timestamp if it fails again. Thanks

**Comment by Logiqx** [comment]
It still doesn't work for me. Auto-uploads to wingfoiling never appear in the upload list.

I can however upload tracks to speedsurfing, foilsurfing and kitesurfing. e.g. 3 uploads as per the image:

![image](https://user-images.githubusercontent.com/17449078/193147080-3024313f-9c45-4a9e-8c47-0ad589c0477f.png)

**Comment by jhdebruin** [comment]
Can you provide the specific file here ?

**Comment by Logiqx** [comment]
Neither of these files will upload for me.

[Speedsurfing20220926170148.zip](https://github.com/djong1/gp3s/files/9679479/Speedsurfing20220926170148.zip)

**Comment by jhdebruin** [comment]
Thnx, just did a few tests,  i think i found out the issue.... will discuss it with @djong1 tomorrow...

**Comment by djong1** [comment]
@Logiqx we fixed a configuration parameter issue, can you validate if it is working now on your side?

**Comment by jhdebruin** [comment]
Test both .fit and .oao , both worked fine now at wingfoiling.com

**Comment by Logiqx** [comment]
> @Logiqx we fixed a configuration parameter issue, can you validate if it is working now on your side?

Yes. I have now been able to succesfully upload these two tracks.
