### ISSUE TITLE
Add Cabrinha as a board, sail and fin manufacturer

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#63]
Required for winging.

TIA

**Comment by jhdebruin** [comment]
Done

**Comment by Logiqx** [comment]
@jhdebruin 

Thanks.

I see there are two Cabrinha brands for sails and fins but there is only one for boards.

Perhaps you can delete the duplicates?

**Comment by jhdebruin** [comment]
Will do some fixes tomorrow...

**Comment by jhdebruin** [comment]
We removed the duplicates for sail and fins

**Comment by Logiqx** [comment]
Thanks
