### ISSUE TITLE
API banner

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#64]
The banner on the API is inconsistent with the rest of the site (waszp vs wing):

![image](https://user-images.githubusercontent.com/17449078/192639665-b106e9f0-a9cf-4301-8cf1-9ba299f7c4e7.png)

vs

![image](https://user-images.githubusercontent.com/17449078/192639614-a1acde08-4d7b-4293-ac4b-3752b7d32256.png)

**Comment by Logiqx** [comment]
p.s. I've added gps-wingfoiling to my event reports:

https://logiqx.github.io/gp3s-query/

**Comment by djong1** [comment]
won't fix for now, we will implement new api portal later this year and do this together
