### ISSUE TITLE
Errors in British Speed Challenges

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#65]
The British Speed Challenges (Fin and Foil) come to an end in 3 days time.

@jhdebruin - Can the following fixes be applied please?

https://logiqx.github.io/gp3s-query/gps-speed/events/710.html
https://logiqx.github.io/gp3s-query/gps-foil/events/707.html

**Comment by Logiqx** [comment]
SSS Go big or go Home 2021-2022 also ends on 30 Sep and requires fixes:

https://logiqx.github.io/gp3s-query/gps-speed/events/715.html

Same for Schildmeer Speed Challenge 2021-2022:

https://logiqx.github.io/gp3s-query/gps-speed/events/704.html

**Comment by jhdebruin** [comment]
@Logiqx  Will schedule them all for next friday !

**Comment by Logiqx** [comment]
Could you maybe run it this week?

It's just that people might be looking at it in the lead up to the last day and not realise there are some glitches.

**Comment by jhdebruin** [comment]
Will give it a run tonight....

**Comment by djong1** [comment]
@Logiqx looking at the foil session from https://www.gps-foilsurfing.com/default.aspx?mnu=user&val=394231&uid=3532&spotid=2430, too me it looks the AVG speed ranking and session list is correct but the script shows a different result. Can you help with this to find the needle in the haystack :-)

**Comment by Logiqx** [comment]
@djong1 - That must have been ephemeral issue, probably due to running the reports whilst rankings were being rebuilt.

Stephen has now disappeared from the error list.

![image](https://user-images.githubusercontent.com/17449078/192748571-e7315f6b-e17b-4aa9-b769-624ea0531142.png)

**Comment by jhdebruin** [comment]
For the record, i did not any rebuilds in the last days...

**Comment by Logiqx** [comment]
@jhdebruin - badly phrased on my part. I meant the automated updates of rankings when a new session is posted.

Stephen's session appears to have been posted around the time when I ran the report.

**Comment by jhdebruin** [comment]
Done the rebuilds of 

704
707
710
715

**Comment by Logiqx** [comment]
3 rebuilds have worked SSS Go Big still has issues:

https://logiqx.github.io/gp3s-query/gps-speed/events/715.html

**Comment by jhdebruin** [comment]
Ok, will have a meeting with Dylan tomorrow evening, lets see if we can fix it than...

**Comment by djong1** [comment]
wont fix, this event has legacy criteria we do not support in the new event module.
