### ISSUE TITLE
API Integration ESP-GPS

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#67]
Build API for auto-uploading ESP-GPS tracks

**Comment by djong1** [comment]
Authentication is a crucial topic, only identified and authenticated endpoints should be able te sent data. Tls is only transport level encryption and not enough. 

Can you handle oauth 2.0? The user authenticate to the gps-speed identity provider and an accestoken is created that the device can use to authenticate to the upload api. 

Other option is to use client certificates for authentication (mtls). However can the certificate distributed securely at device enrollment is quit a challenge.

**Comment by RP6conrad** [comment]
I saw this repository : https://github.com/mobizt/ESP-Signer
At first sight, t should be possible to integrate this on the esp32.

**Comment by djong1** [comment]
work in progress, have a very basic api ready, but need to improve documentation and I will do some additional changes in the url formatting tomorrow. see [https://github.com/djong1/gp3s-trackuploadAPI/tree/main]. So not ready for beta testing, but will be available soon.

**Comment by djong1** [comment]
Updated, @tritondm you can give it a try @jhdebruin @RP6conrad

**Comment by tritondm** [comment]
thanks i give it a try.
