### ISSUE TITLE
Alpha recorded with motion not listed on gps3

### ISSUE THREAD

**Issue by Gerlof5** [djong1/gp3s#68]
Alpha 500 recorded with motion lcd is not uploading to gps3. The alpha is listed on the motion itself and also is listed using gpsactionreplay.com. When uploading the oao-file to gps3, the alpha is not listed.

**Comment by jhdebruin** [comment]
Please include files, screenshots and links to session, without this there is no way we can investigate this. Please notice we use GPS Resulta as backend processing engine, so please check the specific track also with GPS Results, when Alpha is also 0 there, it must be an issue with the device / setttings

**Comment by Gerlof5** [comment]
Laat maar zitten Jan Hendrik, wat een gedoe is dit zeg. Ik krijg op mijn ipad hier geen bestand in geplakt vanuit de map bestanden. Daarnaast heb je de file al, ik doe dit nl nog even voor Janny, zij heeft jou de mail met de track wel gestuurd. Dat ik hem in gpsresults moet checken is ook niet erg servicegericht. Dat programma heb ik niet. Ik heb Julien naar haar track laten kijken en zelf ook in gpsctionreplay werkt het keurig, beide zien we geen problemen met de track alleen gps3 gooit hem eruit. Er zijn meerdere surfers met dit issue heb ik gehoord. Ook Edu heeft hier last van. Dus graag daarnaar kijken. Als je de track van janny alsnog wil hebben mail ik hem wel, maar dit werkt niet met deze site.

**Comment by jhdebruin** [comment]
Checked the file, data fill seems to have lot of rejected datapoints in the track, forward it also to developer of results, could be caused by 10Hz , will investigate 5Hz also

**Comment by jhdebruin** [comment]
[2721_2022-09-09-1102.oao.zip](https://github.com/djong1/gp3s/files/9682612/2721_2022-09-09-1102.oao.zip)

**Comment by Gerlof5** [comment]
Motion staat op 5hz.

**Comment by Gerlof5** [comment]
Ik zie even niet wat je bedoelt Jan Hendrik, kennelijk gaat er iets niet goed, maar wat is mij nog niet duidelijk.

**Comment by jhdebruin** [comment]
@Gerlof5 Call staat al open bij ontwikkelaar van GPS Results, geen actie van jou kant nodig. Juist door hier alles goed vast te leggen en te documenteren kunnen we de issues beter oplossen.... dus we zijn op de goede weg :)

**Comment by jhdebruin** [comment]
Is caused by the minimum speed of 2 kts , this cannot be changed due to much errors in stationary mode, best advise is to turn faster :)

**Comment by Gerlof5** [comment]
Goedemorgen Jan Hendrik, heb het er met Julien ook over gehad en die is er ook ingedoken. Ligt inderdaad aan de minimumspeed, Julien past dit zelf wel toe in zijn nieuwe firmware 3175, want dit zijn de regels van gps3. Janny heeft dan op de motion geen alpha terwijl er op de coros wel een alpha aanwezig is ondanks dat die door de minimumspeed gaat en deze kan vervolgens probleemloos worden geupload naar gos3, dat is wel apart. Dit laatste ter info, misschien dat Manfred daar zelf nog eens naar moet kijken dat de minimumspeed bij de coros niet goed gaat.

Gr
Gerlof

Van: Jan Hendrik de Bruin ***@***.***>
Beantwoorden - Aan: djong1/gp3s ***@***.***>
Datum: donderdag 24 november 2022 om 20:36
Aan: djong1/gp3s ***@***.***>
CC: ***@***.***" ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [djong1/gp3s] Alpha recorded with motion not listed on gps3 (Issue #68)


Is caused by the minimum speed of 2 kts , this cannot be changed due to much errors in stationary mode, best advise is to turn faster :)
