### ISSUE TITLE
When opening "More Session Info" , "View Ranking of the Day"  a "No Data Found"  error occurs , this only happens at spot ID 18723 ( "[Veluwemeer - De oude Pol]" 

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#7]
When opening "More Session Info" , "View Ranking of the Day"  a "No Data Found"  error occurs , this only happens at spot ID 18723 ( "[Veluwemeer - De oude Pol]" 

https://www.gps-speedsurfing.com/default.aspx?mnu=user&val=388582&uid=2954&spotid=18723

**Comment by jhdebruin** [comment]
When chosing this option from the menu the "val=" value is not filled properly, for others spots this is not the case

**Comment by Gertjan9905** [comment]
Hier hetzelfde probleem. Bijvoorbeeld bij mijn laatste sessie, (31-7) staat er no data found. Niet bij alle sessie op de oude pol, maar een paar.
![Screenshot_20220811-221325](https://user-images.githubusercontent.com/111088586/184235131-dacb1bb5-e586-441a-b1ef-d1b37ebdbd06.png)

Ook staat de oude pol niet in de dayranking zoals bijvoorbeeld Polsmaten, Badhoophuizen en strand horst dat wel doen als er gepost word. Je moet steeds inloggen en je sessie opzoeken om je surfsessie te bekijken.

Hopelijk kan er wat aan worden gedaan

**Comment by Gertjan9905** [comment]
Hier de link naar de betreffende sessie die niet opent

https://www.gps-speedsurfing.com/default.aspx?mnu=forum&forum=2&val=

**Comment by jhdebruin** [comment]
Thnx @Gertjan9905 , we need at much info as possible

**Comment by djong1** [comment]
Functional the website does not create a dayranking when a user post a session without a comment. I have changed that now and will monitor if it will be in line with our intention. So you should have your dayranking even when posting without a comment for future sessions, we won't fix it for posted sessions.
