### ISSUE TITLE
Evaluated ranking details are not updated

### ISSUE THREAD

**Issue by raymondwortel** [djong1/gp3s#71]
User 1: https://www.gps-speedsurfing.com/default.aspx?mnu=user&eval=speed_avg&uid=2042&year=2022
User 7: https://www.gps-speedsurfing.com/default.aspx?mnu=user&eval=speed_avg&uid=130&year=2022

The Evil ranking has not been updated when you look at the details.
For this year only month 1 and 2 are visible.

**Comment by kidxrude** [comment]
Really missing this feature in working order too.

**Comment by djong1** [comment]
Note from the developer: Service UpdRankingsByMonthCalcPoint and UpdRankingsByMonthCalcRank are database intense and have been disabled by the throttling service (on purpose).  Need to re-write service to either update in process or use a helper table that can be bulk updated. Need some brain cycles.

**Comment by kidxrude** [comment]
Understandable. And that it takes some time. Just wanted to point this out.

**Comment by jhdebruin** [comment]
Build a new solution, is fixed now

**Comment by kidxrude** [comment]
Thanks for fixing!
