### ISSUE TITLE
Age issues (not me :) )

### ISSUE THREAD

**Issue by raymond-w** [djong1/gp3s#72]
https://www.gps-speedsurfing.com/default.aspx?mnu=rankings&Year=-&Tab=0&Gender=0&WeightClass=0&AgeClass=1&SpeedType=0

There are a lot of riders without a proper age.
They are now in the 0-10/11-14 ranking which now is not usable for the kids.

Maybe add a filter to check registration date and user age.

**Comment by jhdebruin** [comment]
The problem is that users explicitly screw up by providing the wrong date of birth. The best way I see for now is flagging the session, what do you think? @raymondwortel
