### ISSUE TITLE
Uncorrect English translation

### ISSUE THREAD

**Issue by raymondwortel** [djong1/gp3s#78]
https://www.gps-speedsurfing.com/mygps.aspx?mnu=myprofileb2c
I think the English value should be "language", not "culture".

Same as the dropdown value : English US and Enlish UK.

![gps-lang](https://user-images.githubusercontent.com/3018260/193539557-c0f1cd58-0ded-400d-bcca-713d13eb583a.png)

**Comment by djong1** [comment]
fixed, will be published in next release
