### ISSUE TITLE
MyProfile error

### ISSUE THREAD

**Issue by jlbts** [djong1/gp3s#79]
The issue, MyProfile generates a "Sorry...it's not you it's us. oh no an Error 500" error.
This happens on both mobile & desktop, Chrome & Edge.

User Jeroen Labots

Thx in advance for fixing.

**Comment by djong1** [comment]
Hi jeroen, you had a double account, I have de-activated the latest created account. Is it working fine now?

**Comment by jlbts** [comment]
Hi Dylan,I don’t think the second account had ever any impact on my original account. The issue is that there is something wrong with the account, My Profile always generates the following error message:BRJeroenOp 7 nov. 2022 om 21:11 heeft Dylan de Jong ***@***.***> het volgende geschreven:﻿
Hi jeroen, you had a double account, I have de-activated the latest created account. Is it working fine now?

**Comment by djong1** [comment]
welk email gebruik je om aan te melden: hotmail, gmail of consul***?

**Comment by jlbts** [comment]
Hi Dylan,Het gaat om het gmail.com account. Dat is de ‘originele’ (voorheen inlog met consulteert). Hier zit iets niet helemaal lekker, My Profile genereert een error bericht. BRJeroenOp 15 nov. 2022 om 16:26 heeft Dylan de Jong ***@***.***> het volgende geschreven:﻿
welk email gebruik je om aan te melden: hotmail, gmail of consul***?

**Comment by djong1** [comment]
can you check again, fixed a data validation issue

**Comment by jlbts** [comment]
Thanks - this issue has been fixed. Question, on GP3S I can see all my sessions (Beheers sessies). But in GPS-Wingfoiling I cannot see my sessions - and therefore not take out my 111km/h 2sec spike. Is this a similar issue?BRJeroenOp 15 nov. 2022 om 19:07 heeft Dylan de Jong ***@***.***> het volgende geschreven:﻿
can you check again, fixed a data validation issue
