### ISSUE TITLE
"Upload a new track" not working

### ISSUE THREAD

**Issue by CarolinMalsch** [djong1/gp3s#8]
Hi,

I'm facing difficulties when trying to upload a new track since July 23rd (2022). I hope, that someone can help me solving them.

The problem is the following:

When trying to upload a new session, I start with an empty "Uploaded session list"

![image](https://user-images.githubusercontent.com/50137284/181351640-a0178f7a-ed5f-4c86-b90d-3d01797f9a95.png)

Then I choose a track for upload via "Sessions ->Upload Track" ->"Select a track file to upload" and "Submit" it.
The page reloads and the status bar indicates the upload of the track

![image](https://user-images.githubusercontent.com/50137284/181351051-95d4ddd5-591d-4afb-ae23-22fac99656fe.png)

So far so good. 

But the next reload of the page reveals a filled "Uploaded session list". Unfortunately, this list doesn't contain the track that I just wanted to upload but rather previous tracks which are already posted.

![image](https://user-images.githubusercontent.com/50137284/181353061-3b853d52-f6fa-4b2d-a170-99c4cb6dfcc6.png)

I wonder, where do these mysterious tracks come from? And why is the current track not shown in the list with the actual date?

Something else that I've observed is that the status bar is always running, and in the "Upload status - it can take a few minutes"-list there are multiple copies of the track that I'm actually trying to upload (an abnormally large number of replicates).

![image](https://user-images.githubusercontent.com/50137284/181354779-b8d1d20b-5656-46c6-8af7-8f944463582a.png)

It would be great if someone could help me solve that problem.

Best,
Carolin

**Comment by djong1** [comment]
Hi, thanks for submitting this issue. 

1. It looks like you upload a track that consist of many sessions. Please alway's delete your track file on your device before starting a new session. 
2. please delete all existing uploaded track files first by clicking on the delete icon. so you have a clean start.
3. upload the track again, if the session is not listed in the list than it is either missing in the track file or it is invalidated, you can see this when speed calculation is a spinng arrow.

**Comment by djong1** [comment]
we have closed this issue, hope the answer helped to solve the problem.
