### ISSUE TITLE
Gps-wingfoiling - Mijn sessies niet gekoppeld aan post

### ISSUE THREAD

**Issue by WingMic** [djong1/gp3s#81]
Hi, als ik in mijn dashboard naar mijn sessies ga, en ik klik op een sessie, krijg ik niet de sessie te zien. Dan krijg ik de melding “no data found” bij alle sessies die ik gepost heb (10 sessies vanaf 30/8 tot vandaag).

**Comment by jhdebruin** [comment]
Graag even link naar sessies of profiel

**Comment by WingMic** [comment]
https://www.gps-wingfoiling.com/?mnu=user&val=395420&uid=22306

**Comment by WingMic** [comment]
Is dit voldoende? Dan heb je mijn gebruikersnaam e.d.?

**Comment by jhdebruin** [comment]
@WingMic Ik kan probleem niet echt reproduceren, kun je eens proberen volledig opnieuw in te loggen in 'cleane' browser, dus geen cache / cookies etc etc, kan in private browser of incognito mode...

**Comment by WingMic** [comment]
Hi, als ik inlog en ga naar mijn sessies krijg ik nog steeds hetzelfde… 
https://www.gps-wingfoiling.com/mygps.aspx?mnu=mysessions

**Comment by WingMic** [comment]
Welke sessie ik ook klik bij mijn sessies, geen enkele opent de sessie: https://www.gps-wingfoiling.com/?mnu=user&smnu=sessions&uid=22306

**Comment by WingMic** [comment]
Op de spot… op de datum werkt het inderdaad wel zie ik nu.

**Comment by jhdebruin** [comment]
Check, dan sluit ik hem hier eerst even....
