### ISSUE TITLE
Oao file wil niet gedownload worden naar gps3

### ISSUE THREAD

**Issue by Gerlof5** [djong1/gp3s#82]
[](url)

**Comment by jhdebruin** [comment]
@Gerlof5 I've restarted the webuploader for .OAO files, could you please recheck if ok now ?

**Comment by jhdebruin** [comment]
@Gerlof5  Kun je file hier even neerzetten (of mailen naar jbr@gps-speedsurfing.com ) ? Dank !

**Comment by jhdebruin** [comment]
Na reset opnieuw getest, en correcte werking bevestigd
