### ISSUE TITLE
Time table on day ranking doesn't represent correct time data in the track

### ISSUE THREAD

**Issue by kidxrude** [djong1/gp3s#86]
Time table on day ranking doesn't represent correct time data in the track. I'm using a coros vertix, but I think this also goes for other type of devices and so datasources. See the screenshot for details. I've started my session around 10:00 o'clock and the time table in the dayranking places my first speed run at 8:01 o'clock. My device definitely contains the right data (see screenshot of reading out an coros app exported .gpx track).

![Screenshot 2022-10-17 at 09 08 24](https://user-images.githubusercontent.com/9435/196113089-d6eae953-4f20-40dc-bf89-e7c2209645b9.png)
![Screenshot 2022-10-17 at 09 13 57](https://user-images.githubusercontent.com/9435/196113097-2406135b-55d3-4a6b-aba2-de7d5a685866.png)

**Comment by djong1** [comment]
1. is the timeline shifted for all riders on that day, or is only your timeline shifted? 
2. The time shown is UTC, so you would like to shift it to a local time correct?

**Comment by djong1** [comment]
implemented with shifted timezones

**Comment by kidxrude** [comment]
Thank you for fixing! It does look to be more correct now. What do you mean with 'with shifted timezones'?
