### ISSUE TITLE
Graphical overview on map of spots where has been posted in the past

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#87]
Request to make a graphical map with spots on it where already has been posted in the past, to make it more easier to explore good spots near you - > Comparable with wind-app Wisuki 
![image0](https://user-images.githubusercontent.com/109060128/196186239-a4203248-6ee6-49d9-843f-b809c6d09016.png)

**Comment by djong1** [comment]
Personal view: build it based on sample sample https://github.com/Azure-Samples/AzureMapsCodeSamples/blob/main/Samples/Symbol%20Layer/Display%20clusters%20with%20a%20Symbol%20layer/Display%20clusters%20with%20a%20Symbol%20layer.html

- Show the spots that have been visited in the past x period, use cluster mode on map 
- when selecting the spot icon show the statistics: https://github.com/Azure-Samples/AzureMapsCodeSamples/blob/main/Samples/Symbol%20Layer/Create%20Symbols%20from%20Custom%20JSON/Create%20Symbols%20from%20Custom%20JSON.html

**Comment by djong1** [comment]
Views:

Point details:
- speed_avg
- sessions_posted (all-time)
- sessions_posted (this_year)
- spot link
- top poster username


spots viewer - popular spots
- geojson with all spots
- cluster bubble size based on nr sessions posted  
- show sessions in image for point
- on-click show spot point details 
- 

spots viewer - best speed spots
- geojson with all spots
- cluster bubble size based on speed_avg
- show speed in image for point
- - on-click show spot point details 

personal spot heat map (all time)
- geojson per user (premium only)
- - cluster bubble size based on nr sessions posted  
- show sessions in image for point
- on-click show spot point details 

last 48 hour session posted heat map (use hetamap) and export image

**Comment by jhdebruin** [comment]
Today we have introduced our new Speed Spot Search Engine, based on the feedback we received from our community, its now available for all premium members and can be found here -> [https://www.gps-speedsurfing.com/mygps.aspx?mnu=spotssearch](url)
It will present a graphical overview of the most popular speedspots worldwide, Zoom in to see more details about spots, "blue" dots are most popular area's, "grey" dots are less popular spots, you can zoom in until you see the "spot marker", you can click the markers to see more information about the spot and link to the spot details page. 

![Screenshot 2023-08-14 at 18 59 27](https://github.com/djong1/gp3s/assets/109060128/e87b17f7-2b0d-4689-8113-c99d7121d77b)

For any comments / feedback please our GitHub page for this [https://github.com/djong1/gp3s/issues/87](url)

**Comment by Rolf177** [comment]
Gp3s geeft aan dat ik geen premium member ben en kan de pagina dus niet openen. Ik ben wel premium member dus ben benieuwd waar dit aan ligt.

**Comment by jhdebruin** [comment]
Make sure you are logged in first and then open this url

https://www.gps-speedsurfing.com/mygps.aspx?mnu=spotssearch

**Comment by djong1** [comment]
Update: fixed dark popup issue (unreadable text)

**Comment by djong1** [comment]
Update: made it multisport aware, so it works now also for foil / wing and ice

**Comment by djong1** [comment]
Close for now: 
- feature implemented for spot search and best speed search 
- feature not implemented for personal view given the low number of reactions from the community, looks like there is no desire to have this feature

Open:
- batch worker to generate GEOJSON on scheduled bases

**Comment by djong1** [comment]
Batch worker implemented -> close topic as completed

**Comment by kidxrude** [comment]
Love the feature. Just one thing, I'm not seeing a specific spot I frequently attend and post on. What could be the problem?
Link (found through the link in a session detail page) to the spot itself for reference: https://www.gps-speedsurfing.com/mygps.aspx?mnu=spotsearch&val=5781

**Comment by djong1** [comment]
Location seems to be a bit off it is in the sea left from Corse.

**Comment by kidxrude** [comment]
> Location seems to be a bit off it is in the sea left from Corse.

OK, thanks for clarifying. But is it fixable? I would really like it to be in the right spot.

**Comment by djong1** [comment]
can you give me a location lat long for the spot?
________________________________
Van: kidxrude ***@***.***>
Verzonden: vrijdag 25 augustus 2023 18:56
Aan: djong1/gp3s ***@***.***>
CC: Dylan de Jong ***@***.***>; State change ***@***.***>
Onderwerp: Re: [djong1/gp3s] Graphical overview on map of spots where has been posted in the past (Issue #87)


Location seems to be a bit off it is in the sea left from Corse.

OK, thanks for clarifying. But is it fixable? I would really like it to be in the right spot.

**Comment by kidxrude** [comment]
> Location seems to be a bit off it is in the sea left from Corse.

39.091836729893906, 8.443351552037011

[https://www.google.nl/maps/place/Windsurfing+Club+Sa+Barra+Scuola+Kitesurf+Windsurf+Wingfoil/@39.0941908,8.4393167,16z/data=!4m15!1m8!3m7!1s0x12e7aa5ba510380f:0x74e7253d56b27c34!2s09017+Sant'Antioco+South+Sardinia,+Italië!3b1!8m2!3d39.0689813!4d8.454395!16s%2Fg%2F12xpwjnr_!3m5!1s0x12e7aa2cf22adbcb:0x54516434a00d773e!8m2!3d39.091498!4d8.4413346!16s%2Fg%2F11bz0xtzhj?entry=ttu]

**Comment by djong1** [comment]
updated, will be processed in the update batch end of week

**Comment by LucSalomons** [comment]
Map is not visible to me.  (Chrome on Mac) 
<img width="879" alt="image" src="https://github.com/djong1/gp3s/assets/143724473/5572e684-8117-46d1-b76f-788ac41ff0e9">

**Comment by jhdebruin** [comment]
Could you also give it a try with Safari or Edge ?

**Comment by kidxrude** [comment]
Same for me on Safari on iOS. Map doesn’t show.Sent from my iPhoneOn 6 Sep 2023, at 18:18, Jan Hendrik de Bruin ***@***.***> wrote:﻿
Could you also give it a try with Safari or Edge ?

**Comment by jhdebruin** [comment]
@kidxrude Not sure it was designed to use on IOS, but thnx for the feedback

**Comment by kidxrude** [comment]
Ha ok! It’s only the second most used browser nowadays. 😎No worries, I’ll find the screen on my laptop. 👍Sent from my iPhoneOn 6 Sep 2023, at 19:45, Jan Hendrik de Bruin ***@***.***> wrote:﻿
@kidxrude Not sure it was designed to use on IOS, but thnx for the feedback

**Comment by jhdebruin** [comment]
I've moved this one to https://github.com/djong1/gp3s/issues/218  , so please put your comments there, lets see if this possible at all ...
