### ISSUE TITLE
SSL certificates invalid

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#88]
This problem occurs when accessing [gps-kitesurfing.com](https://gps-kitesurfing.com), [gps-foilsurfing.com](https://gps-foilsurfing.com) or [gps-wingfoiling.com](https://gps-wingfoiling.com) without specifying the www subdomain.

![image](https://user-images.githubusercontent.com/17449078/197405515-519b3c1c-77fd-4032-b488-973ee2c369c4.png)

**Comment by djong1** [comment]
expect delivery end of week

**Comment by jhdebruin** [comment]
Checked and fixed
