### ISSUE TITLE
HTTP re-directs missing

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#89]
It is possible to access [http://gps-speedsurfing.com/](http://gps-speedsurfing.com/) and it re-directs to [https://gps-speedsurfing.com/](https://gps-speedsurfing.com/)

This does not apply to [http://gps-kitesurfing.com/](http://gps-kitesurfing.com/), [http://gps-foilsurfing.com/](http://gps-foilsurfing.com/) or [http://gps-wingfoiling.com/](http://gps-wingfoiling.com/) which all results in HTTP error 404.

![image](https://user-images.githubusercontent.com/17449078/197405677-fcb433c3-692f-4adb-a68b-5f76e4751836.png)

![image](https://user-images.githubusercontent.com/17449078/197405686-902d4a79-d932-4a15-abf3-219c683367ec.png)

![image](https://user-images.githubusercontent.com/17449078/197405707-845f5cd9-4ece-490b-b178-fadcb77ea91c.png)

**Comment by jhdebruin** [comment]
Checked and fixed
