### ISSUE TITLE
Duplicate entries in rankings

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#9]
Sometimes there are duplicate entries in event rankings:
 
[British Foil Speed Challenge 2022 - Average Speed](https://www.gps-foilsurfing.com/default.aspx?mnu=eventranking&val=707) - Michael George, Garry Connel, Sinon Chippington and Nic Dodd are listed twice.

This problem also exists in the overall rankings:

[Overall Rankings by Country - UK, Average Speed](https://www.gps-foilsurfing.com/default.aspx?mnu=rankings&Year1=-&countryID1=268&Gender1=0&Tab=1&WeightClass1=0&AgeClass1=0&SpeedType1=0) - Richard Beaman (#11 and #12) and Alex Smith (#17 and #18) are listed twice.

These are just examples and the problem also exists elsewhere.

**Comment by Logiqx** [comment]
Further information which may be useful...

The rebuild of UID 2640 on event ID - 707 (BFSC 2022) removed the duplicate entry for Michael George.

The rebuild of user 2640 (Michael George) was done by @jhdebruin for issue #10.

**Comment by jhdebruin** [comment]
check, thnx , will do a rebuild for this users also

**Comment by jhdebruin** [comment]
Did the first rebuild of the event, all duplicates seems to be fixed now

[British Foil Speed Challenge 2022 - Average Speed](https://www.gps-foilsurfing.com/default.aspx?mnu=eventranking&val=707) - Michael George, Garry Connel, Sinon Chippington and Nic Dodd are listed twice.

**Comment by jhdebruin** [comment]
@Logiqx Fixed also the country ranking

**Comment by Logiqx** [comment]
Thanks. Manual rebuild looks to have done the job.

I guess the original bug will also need fixing to avoid it re-occurring?

**Comment by jhdebruin** [comment]
@Logiqx Yes, but @djong1 already has deployed the permanent solution

**Comment by Logiqx** [comment]
Quick note to say that future duplicates can be seen on this page - https://logiqx.github.io/gp3s-query/events/

Just be sure to check "last refreshed" at the top of the page.

**Comment by Logiqx** [comment]
@jhdebruin - duplicates remain on 2022 Funsport Makkum GPS Speed Challenge:

https://logiqx.github.io/gp3s-query/events/740.html

Due to the success of previous rebuilds, probably worth attempting a rebuild.
