### ISSUE TITLE
Additional sail brands for wing foiling

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#91]
The following hand wing brands are popular and need to be added to the list of "sail" brands:

PPC
... others TBC

**Comment by jhdebruin** [comment]
@Logiqx i don't get the "... others TBC"  , what do you mean with this ?

**Comment by Logiqx** [comment]
"others too be confirmed",  I ran out of time when I created this ticket.

I'll check what is available and add some popular brands (but missing) when I get a chance.

**Comment by jhdebruin** [comment]
Allright, that's ok :) TBC sounds ok than !
