### ISSUE TITLE
Runs map overview not possible to review the run in the 500m indication

### ISSUE THREAD

**Issue by kidxrude** [djong1/gp3s#92]
In the runs map overview it's never possible to review all 5 runs because the 500m run always overlaps one of the runs. At least that's how it looks like to me. 
![image](https://user-images.githubusercontent.com/9435/200784364-5cb3191e-2e86-4e45-81df-402773514176.png)

**Comment by djong1** [comment]
Correct in most cases these overlap. Added it on special request from other riders. Option 1 is leave 500 meter out or go ahead with current view. Please comment @everyone

**Comment by kidxrude** [comment]
There's already mostly two map views (I don't know exactly why). So why not have the 5x 10sec runs and the 500m display each in it's own map view?

**Comment by djong1** [comment]
removed 500
