### ISSUE TITLE
Not all sessions are included in DSC Event

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#93]
Not all sessions are automatically included in the DSC Event (Worldwide) 

https://www.gps-speedsurfing.com/default.aspx?mnu=event&val=760

**Comment by djong1** [comment]
Please rebuild event with admin module, new sessions should be added automatically now.

**Comment by jhdebruin** [comment]
Additional fixes are needed, lets try to fix it this week at our teammeeting

**Comment by jhdebruin** [comment]
Fixed for all platforms
