### ISSUE TITLE
Weird alpha results

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#98]
I was just looking at the alpha rankings on gps-wingfoiling and noticed this 29.46 knot alpha at the top.

Something is clearly amiss in some piece software; either the auto-upload or whatever uploaded the session.

https://www.gps-wingfoiling.com/default.aspx?mnu=user&val=396909&uid=26260&spotid=25

![image](https://user-images.githubusercontent.com/17449078/202759342-4c3edea3-63c6-4954-ba23-bf5e377c133a.png)

**Comment by jhdebruin** [comment]
Posted with non-approved device, so this is possible, best is to flag this session so rider can correct it
