### ISSUE TITLE
When trying to add new type of fin of existing brands wrong brand list appears

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#99]
When trying to add a new fin of an existing brand , the wrong brand lists ( in this case boards brands instead of fin brands) appears in the pull down list![image](https://user-images.githubusercontent.com/109060128/202839024-f2a60aa1-daab-4432-be90-6046a8e7cbca.png)

**Comment by jhdebruin** [comment]
![image](https://user-images.githubusercontent.com/109060128/202839038-bdfb6a87-e40d-4bf5-960f-891a724981e6.png)

**Comment by djong1** [comment]
solved, available after next release

**Comment by jhdebruin** [comment]
25 11 check if fixed

**Comment by jhdebruin** [comment]
Checked and fixed

**Comment by jhdebruin** [comment]
![Schermafbeelding 2022-12-04 om 17 27 40](https://user-images.githubusercontent.com/109060128/205504260-4f81bd3f-ee58-4a76-b0a2-003084471800.png)

**Comment by jhdebruin** [comment]
Issue has not been solved correctly, still Board Brands appear instead of Fin Brands

**Comment by jhdebruin** [comment]
Loopt deployment nog ? Krijg een 500 op inloggen…

[Graphical user interface, website  Description automatically generated]

From: Dylan de Jong ***@***.***>
Date: Monday, 5 December 2022 at 15:18
To: djong1/gp3s ***@***.***>
Cc: Jan hendrik de Bruin ***@***.***>, State change ***@***.***>
Subject: Re: [djong1/gp3s] When trying to add new type of fin of existing brands wrong brand list appears (Issue #99)

please validate again (was propagated to new environment, new environment is now live)

**Comment by jhdebruin** [comment]
fixed and confirmed 

![image](https://user-images.githubusercontent.com/109060128/205704222-f88959df-76fc-4233-89b1-e82c5aafbbd3.png)
